### ISSUE TITLE
3.	Dummy titles (Mail Bart Havermans 22/02/2022)

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#102]
Tests are grouped under titles. Some generic tests are placed under a dummy title (title without a label). How do we need to send this in FHIR
![image](https://user-images.githubusercontent.com/90335317/155360009-0ccd4819-978c-4dd9-aa70-59dd212004a5.png)
![image](https://user-images.githubusercontent.com/90335317/155360035-2edf2f31-9f23-4b85-9084-6121e41f3136.png)

Now as text a ‘?’ is send. What are options to use an empty title?

![image](https://user-images.githubusercontent.com/90335317/155360118-9ac39c40-4174-49d6-a1ae-9479c4293f2c.png)

**Comment by LotteAd** [comment]
To tackle empty titles, we thoroughly use the "hasMember" tag of the Observation member and the Result Reference tag of the DiagnosticReport member to create a logical structure.
Easiest is to explain this with a couple of examples.

**Example 1: a test result as the first line of a report, without a subtitle above the test result**
For this, we refer to the test (and the following subtitles after this test) at the level of the DiagnosticReport:
> "result": [
>             {                "reference": "Observation/Observation.0.0.0.1"            },
>             {                "reference": "Observation/Observation.1.0.0.0"            },
>             {                "reference": "Observation/Observation.2.0.0.0"            },
>             {                "reference": "Observation/Observation.3.0.0.0"            },
>             {                "reference": "Observation/Observation.4.0.0.0"            },
>             {                "reference": "Observation/Observation.5.0.0.0"            },
>             {                "reference": "Observation/Observation.6.0.0.0"            }
>         ]
> 
Observation.0.0.0.1 is the test without a title, the other Observations are main titles.

**Example 2: a test result with an empty (sub)title**
Here, we use the hasMember tag to correctly refer to the position of the test in the tree structure.
```
"hasMember": [
            {                "reference": "Observation/Observation.1.0.0.1"            },
            {                "reference": "Observation/Observation.1.0.0.2"            },
            {                "reference": "Observation/Observation.1.0.0.3"            },
            {                "reference": "Observation/Observation.1.0.0.4"            },
            {                "reference": "Observation/Observation.1.0.0.5"            },
            {                "reference": "Observation/Observation.1.0.0.6"            },
            {                "reference": "Observation/Observation.1.0.0.7"            },
            {                "reference": "Observation/Observation.1.1.0.0"            },
            {                "reference": "Observation/Observation.1.2.0.0"            },
            {                "reference": "Observation/Observation.1.3.0.1"            },
            {                "reference": "Observation/Observation.1.3.0.2"            }
        ]
```
This "hasMember" refers from the main title "Hematology". Observations 1.0.0.1 through 1.0.0.7 are tests directly under the main title "Hematology". Observations 1.1.0.0 and 1.2.0.0 are subtitles (which each also have their own hasMembers).
Observations 1.3.0.1 and 1.3.0.2 are observatios underneath an empty subtitle, which means we already refer to them from this main title.


The question to ask with empty titles is always to check on which level the empty title should be, and then refer to the tests at that level.

**Comment by bdc-ehealth** [comment]
Proposal: we put this in the guidance...
