### ISSUE TITLE
Microbiology reporting in FHIR

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#105]
Dear all,
 
In a first try to report some microbiology in FHIR, it seems that is not yet clear how to report it in a structured way. Based on the examples for Mips and Macsys it seems like there is a different approach to report a microbiology exam. During the next meeting we should discuss how to report a microbiology exam in FHIR.
 
Some aspects must be considered.
 
A sample can have multiple microbiology cultures
-	Aerobic
-	Anaerobic
-	Yeasts
-	Fungi
 
A culture can be negative or can consist out of 1 of more identified germs. Each germ has a specific SCT code.
 
It is also possible that on a germ a specific isolation test is reported, which has a specific LOINC code. E.g. ESBL, Beta-Lactamase,…
 
When a culture is positive, it is possible to perform an antibiogram. There are specific LOINC codes for an antibiogram
-	Aerobic antibiogram
-	Anaerobic antibiogram
-	Yeasts antibiogram
-	Fungi antibiogram
-	…
 
An antibiogram can consist out of 1 of more antibiotics. And an antibiotic can have multiple LOINC codes. E.g.
-	16-6  ( [https://loinc.org/16-6/](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-eu.mimecast.com%2Fs%2F8RyLCxnk5FW4gyuYFDgM%3Fdomain%3Dloinc.org%2F&data=04%7C01%7Cbart.havermans%40mips.be%7C97622ab8bcce4a1f993608d9fb56a84d%7Cbe232667461545fd9ce747b94ce10de7%7C0%7C0%7C637817171875416283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LphLkyV50N49Z8vSjxS3atU3ugyl%2B0DhEIcxhf8nElQ%3D&reserved=0)  : Amoxicillin [Susceptibility] by Minimum inhibitory concentration (MIC) )
-	6976-5 ([https://loinc.org/6976-5/](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-eu.mimecast.com%2Fs%2FTttMCyoP5FBzQgFRNRJQ%3Fdomain%3Dloinc.org%2F&data=04%7C01%7Cbart.havermans%40mips.be%7C97622ab8bcce4a1f993608d9fb56a84d%7Cbe232667461545fd9ce747b94ce10de7%7C0%7C0%7C637817171875416283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E5oza6vza1C7DkluY6HdW2jkUpYLUCTo1GY7c95MFKo%3D&reserved=0) : Amoxicillin [Susceptibility] by Gradient strip)
-	17-4 ( [https://loinc.org/17-4/](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-eu.mimecast.com%2Fs%2FG0-HCzvp5sjpy3Fo2chI%3Fdomain%3Dloinc.org%2F&data=04%7C01%7Cbart.havermans%40mips.be%7C97622ab8bcce4a1f993608d9fb56a84d%7Cbe232667461545fd9ce747b94ce10de7%7C0%7C0%7C637817171875416283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Buz5%2BS9EWZ6lgdM2z9HL3aAxGcd92gl%2BnJCsu57dOp4%3D&reserved=0) : Amoxicillin [Susceptibility] by Disk diffusion (KB) )
-	18861-5 ( [https://loinc.org/18861-5/](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-eu.mimecast.com%2Fs%2FUIS9CANDouD3PgiMQIPM%3Fdomain%3Dloinc.org%2F&data=04%7C01%7Cbart.havermans%40mips.be%7C97622ab8bcce4a1f993608d9fb56a84d%7Cbe232667461545fd9ce747b94ce10de7%7C0%7C0%7C637817171875416283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JBRBc2qep8LUer5%2Fb7Vv1hGjHEVr%2BAV57Spt8KRjGK4%3D&reserved=0) : Amoxicillin [Susceptibility] / RIS )
 
On some levels (culture, germ, antibiotic) it is possible to report some comments. 
 
If we put this into a scheme, it looks like this. We should agree if this is the way we want to report microbiology in FHIR syntax or that the is a different way of processing it.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NL style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal><span lang=NL-BE style='mso-ansi-language:NL-BE'><o:p>&nbsp;</o:p></span></p>

Level 1 | Level 2 | Level 3 | Level 4 | Level 5 | Level 6 | FHIR
-- | -- | -- | -- | -- | -- | --
Sample |   |   |   |   |   | Specimen
  | Aerobic culture |   |   |   |   | Observation with LOINC code and possible note is there is   a general comment on culture level.   It might have child observations for each detected germ.
  |   | Germ 1 |   |   |   | Observation with coding system SCT for the identified germ   and possible note for comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase)
  |   |   | Aerobic antibiogram |   |   | ???
  |   |   |   | Antibiotic A |   | ??? Subtitle ???
  |   |   |   |   | RIS value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | MIC value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | E-Test value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | Agar value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   | Antibiotic B |   | ??? Subtitle ???
  |   |   |   |   | RIS value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | MIC value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | E-test value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | Agar value | Observation with specific LOJNC code and possible note for   comment
  |   |   | Isolation test 1 |   |   | Observation with a specific LOINC code.
  |   | Germ 2 | No antibiogram |   |   | Observation with coding system SCT for the identified germ   and possible note for comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and child observations for the antibiotic results
  |   | Germ 3 |   |   |   | Observation with coding system SCT for the identified germ   and possible note for comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and child observations for the antibiotic results
  |   |   | Aerobic antibiogram |   |   | ???
  |   |   |   | Antibiotic A |   | ??? Subtitle ???
  |   |   |   |   | RIS value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | MIC value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | E-test value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | Agar value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   | Antibiotic C |   | ??? Subtitle ???
  |   |   |   |   | RIS value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | MIC value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | E-test value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | Agar value | Observation with specific LOJNC code and possible note for   comment
  | Anaerobic culture |   |   |   |   | Observation with specific LOINC code and child   observations for each germ and no result
  |   | Germ 1 |   |   |   | Observation with coding system SCT for the identified germ   and possible note for comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and child observations for the antibiotic results
  |   |   | Anaerobic antibiogram |   |   | ???
  |   |   |   | Antibiotic A |   | ??? Subtitle ???
  |   |   |   |   | RIS value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | MIC value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | E-test value | Observation with specific LOJNC code and possible note for   comment
  |   |   |   |   | Agar value | Observation with specific LOJNC code and possible note for   comment
  |   | Germ 2 |   |   |   | Observation with coding system SCT for the identified   germ.
  | Yeasts culture | Negative, no germs deteced |   |   |   | Observation with specific LOINC code and a value.

<p class=MsoNormal><span lang=EN-US style='color:black;mso-ansi-language:EN-US'>&nbsp;</span><span
lang=NL-BE style='mso-ansi-language:NL-BE'><o:p></o:p></span></p>

</body>

</html>

Feel free to give some comments.

**Comment by thibaultmh** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/THIBAU~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NL style='tab-interval:35.4pt;word-wrap:break-word'>


<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>After some
internal discussions, it is not the logic of the FHIR translator to a
(sub)titles to make it more readable, this is the responsibility of the
visualizer how shows the information. We should send it in a structured way.</span><span
lang=NL-BE style='mso-ansi-language:NL-BE'><o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>We believe
there is also no specific LOINC code an antibiogram. Soo the layout might be
simplified</span><span lang=NL-BE style='mso-ansi-language:NL-BE'><o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>&nbsp;</span><span
lang=NL-BE style='mso-ansi-language:NL-BE'><o:p></o:p></span></p>



Level 1 | Level 2 | Level 3 | Level 4 | FHIR
-- | -- | -- | -- | --
Sample |   |   |   | Specimen
  | Aerobic culture |   |   | Observation with LOINC code   It might have child observations for each detected germ.   In case there is no germ detected, the negative answer will be reported as   result of this observation.
  |   | Germ 1 |   | Observation with coding system SCT for the identified germ   and possible note for external comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and a child note to the antibiogram
  |   |   | RIS value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | MIC value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | E-Test value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Agar value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | RIS value Antibiotic B | Observation with specific LOJNC code and possible note for   external comment
  |   |   | MIC value Antibiotic B | Observation with specific LOJNC code and possible note for   external comment
  |   |   | E-test value Antibiotic B | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Agar value Antibiotic B | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Isolation test 1 | Observation with a specific LOINC code.
  |   | Germ 2 | No antbiogram | Observation with coding system SCT for the identified germ   and possible note for external comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and a child note to the antibiogram
  |   | Germ 3 |   | Observation with coding system SCT for the identified germ   and possible note for external comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and a child note to the antibiogram
  |   |   | RIS value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | MIC value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | E-test value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Agar value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | RIS value Antibiotic C | Observation with specific LOJNC code and possible note for   external comment
  |   |   | MIC value Antibiotic C | Observation with specific LOJNC code and possible note for   external comment
  |   |   | E-test value Antibiotic C | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Agar value Antibiotic C | Observation with specific LOJNC code and possible note for   external comment
  | Anaerobic culture |   |   | Observation with specific LOINC code and child   observations for each germ and no result
  |   | Germ 1 |   | Observation with coding system SCT for the identified germ   and possible note for external comment on germ level.   It might have child observation for each isolation test (e.g. ESBL /   Beta-lactamase) and a child note to the antibiogram
  |   |   | RIS value antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | MIC value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | E-test value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   |   | Agar value Antibiotic A | Observation with specific LOJNC code and possible note for   external comment
  |   | Germ 2 |   | Observation with coding system SCT for the identified   germ.
  | Yeasts culture | Negative, no germs detected |   | Observation with specific LOINC code and a value.



<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>&nbsp;</span><span
lang=NL-BE style='mso-ansi-language:NL-BE'><o:p></o:p></span></p>


</body>

</html>

**Comment by bdc-ehealth** [comment]
@costateixeira What do other countries do for Microbiology?

Proposal of the group: Do the microbiologists agree with the second proposal above?

Is the SNOMED-CT code for germs optional? Is text only sufficient?

SIR in interpretation or in value?

**Comment by bdc-ehealth** [comment]
The WG decides that if the string value of the result field contains a newline character, the contents should be rendered in a non-proportional font. This will be added to the guidance.

**Comment by FrederikVds** [comment]
> We will use the CodeableConcept to indicate RIS. For the RIS specific LOINC code we put it in both the value and the interpretation.

Hi @bdc-ehealth,

We put our coded values in the value field:
```
<valueCodeableConcept>
<coding>
<system value="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"/>
<code value="S"/>
<display value="S"/>
</coding>
<text value="S"/>
</valueCodeableConcept>
```

Are you saying you also want us to interpret S as being S? As follows:
```
<valueCodeableConcept>
<coding>
<system value="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"/>
<code value="S"/>
<display value="S"/>
</coding>
<text value="S"/>
</valueCodeableConcept>
<interpretation>
<coding>
<system value="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"/>
<code value="S"/>
<display value="S"/>
</coding>
</interpretation>
```

We currently don't support custom codings for the interpretation field. Only general ones like low, high, ... In our system, R, I and S go into the value field. Is this incorrect?

**Comment by bdc-ehealth** [comment]
@FrederikVds ,

if you use a codeableconcept in the value, this is fine. If you use a string in the value, then there is an issue that the interpretation should use the codeableconcept: https://github.com/hl7-be/lab/issues/105#issuecomment-1068163733
