### ISSUE TITLE
Antibiotic result interpretations

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#106]
In issue https://github.com/hl7-be/hl7-be-fhir-laboratory-report/issues/81 we limited the interpretation codes. This is too strict, I would add RIS to the interpretations. This is needed for antibiotic results.

For reference, the allowed interpretation codes:
http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/ValueSet-be-vs-observation-interpretation.html

**Comment by bdc-ehealth** [comment]
No problem, RIS can be added

**Comment by FilipMigom** [comment]
Can someone explain why this valueset is limited ?
I can think of other Interpretations in Microbiology to be supported too : See SSD 
See also: https://build.fhir.org/valueset-observation-interpretation.html

**Comment by FilipMigom** [comment]
I also believe that the reporting of Microbiology Isolations can be reported with an Interpretation NEG or POS.
USE-CASE : Report an isolation with an indication if this is seen POS or not NEG.
This is how our Germans have implemented the FHIR Diagnostic Report within DEMIS/RKI

**Comment by bdc-ehealth** [comment]
The group decides to remove the limitation.
