### ISSUE TITLE
ACTH system URL

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#108]
Hi,

In Wallonia they want to also use ACTH for the 'observation.code'. This would be used for codes that are not in LOINC or ALBERT. This does not seem to contradict the guidance. What does the WG think?

If we decide to use this code set, what system URL should we use? I propose:
https://www.ehealth.fgov.be/standards/fhir/CodeSystem/acth

Best,
Thibault

**Comment by FilipMigom** [comment]
Discussed during HL7 Belgium FHIR meeting.
Currenlty : the LIS solutions are able to export the LocalCode + alternative CODE (typically in this case LOINC)
Allowing the export an other alternative code ALBERT 
or even a 3th alternative code ACTH is not supported by the LIS solutions.
A complex setup and extra development will be required to support this

**Comment by bdc-ehealth** [comment]
The WG decides that the ACTH code can be used according to the rules described in the guidance. The url will not be part of the standard.
