### ISSUE TITLE
visualisation microbiology

### ISSUE THREAD

**Issue by tomfiers** [hl7-be/lab#114]
microbiology indentation is strange. 
Think visualiser? Or message? 
- The first one is under culture, but the comment of the cephalosporins is same level as a title, so that the other germs fall immediately under "intrinsic resistance" (also for parabacteroides, which seems to be a new title, and does not seem to relate only to the KIEM++ above it.
-  I would expect the antibiogram to indent slightly in terms of the level versus the germ it relates to.
- that S and R stay with quite a lot of useless text which belongs in the attributes

![image](https://user-images.githubusercontent.com/99816947/162951210-631d18ed-2eaf-494c-9a1d-4e85712e3b36.png)

![image](https://user-images.githubusercontent.com/99816947/162952613-a1f6a804-3d9c-4626-8167-e29e7bf78172.png)

**Comment by bdc-ehealth** [comment]
@tomfiers can you please add the json file to the issue? Or a reference to the file that is maybe already in GitHub?

**Comment by tomfiers** [comment]
https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/MIPS/UZG_scenario9
scenario 9A2 structured

**Comment by bdc-ehealth** [comment]
Will be handled in https://be-ehealth-standards.atlassian.net/jira/servicedesk/projects/ESI/queues/custom/19/ESI-7

**Comment by bdc-ehealth** [comment]
@tomfiers Update is ready
