### ISSUE TITLE
URL in readme results in 404.

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#133]
The URL http://build.fhir.org/ig/hl7-be/lab/branches/main/index.html found in the [readme](https://github.com/hl7-be/lab/blob/master/README.md?plain=1#L8) results in a 404.

**Comment by MatthiasDM** [comment]
Can this be fixed please?

**Comment by bdc-ehealth** [comment]
@MatthiasDM @FlorianBonte-Moonchase 
Hello Matthias and Florian, this issue is fixed.
