### ISSUE TITLE
Example resources result in validation errors in visualisation tool

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#134]
The JSON FHIR resources as found e.g. here: http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/Bundle-antibiogramIsNegativeAsBundleCollection.json

result in errors when uploaded through the [FHIR visualisation tool](https://vizapp.icure.dev/).

**Comment by bdc-ehealth** [comment]
@FlorianBonte-Moonchase [http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report](http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report) is an outdated URL. Where did you get it from?

**Comment by FlorianBonte-Moonchase** [comment]
Updated link:

http://build.fhir.org/ig/hl7-be/lab/Bundle-antibiogramIsNegativeAsBundleCollection.json.html

When uploaded through the tool, no errors were found.
