### ISSUE TITLE
Display of text when there is no code display available (Mail de Stefan Waegemans 30/08/2022)

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#137]
•	For bacteriology reports, we requested that the valueCodeableConcept.Text would be displayed if no valueCodeableConcept.coding.display is available. We see that this issue has not been fixed.
Example:
 
 
![pic1](https://user-images.githubusercontent.com/90335317/187619735-bf5d7e7c-5b60-41d4-bd47-e4047d8db6ec.png)
![pic2](https://user-images.githubusercontent.com/90335317/187619851-70481284-9164-42d4-8a12-b96c671c5fab.png)

**Comment by bdc-ehealth** [comment]
@LotteAd 

Ok, we did not understand this from any of the previous questions, but no problem, we are on to it.

**Comment by bdc-ehealth** [comment]
@LotteAd 

Hebben we dit goed begrepen?

Hello,

Pour être bien sûr d’avoir compris la priorité l’affichage attendu :

      "valueCodeableConcept": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
          "code": "R",
"display": "Intrinsieke resistentie1"
        } ],
               "text" : "Intrinsieke resistentie2"

->	Intrinsieke resistentie1

      "valueCodeableConcept": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
          "code": "R"
        } ],
            "text" : "Intrinsieke resistentie2"

->	Intrinsieke resistentie2
      
"valueCodeableConcept": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
          "code": "R"
} ]
      -> R

**Comment by LotteAd** [comment]
This would be one of our examples:
"valueCodeableConcept": {
            "coding": [
                {
                    "system": http://www.macsys.be/hl7/kiemcode,
                    "code": "MED-PSEAE"
                }
            ],
            "text": "Pseudomonas aeruginosa"
        },

Right now, the code is displayed (by lack of a “display” field without the coding field), but we would like to see the text-field displayed, as this is human readable.

Van: Bart Decuypere (eHealth) ***@***.***>
Verzonden: woensdag 31 augustus 2022 11:42
Aan: hl7-be/lab ***@***.***>
CC: Lotte Adriaensen ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [hl7-be/lab] Display of text when there is no code display available (Mail de Stefan Waegemans 30/08/2022) (Issue #137)


OPGELET: Deze boodschap komt van een externe partij. Wees steeds voorzichtig bij het openen van bijlagen en links.

@LotteAd<https://github.com/LotteAd>

Hebben we dit goed begrepen?

Hello,

Pour être bien sûr d’avoir compris la priorité l’affichage attendu :

  "valueCodeableConcept": {



    "coding": [ {



      "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",



      "code": "R",



"display": "Intrinsieke resistentie1"
} ],
"text" : "Intrinsieke resistentie2"

-> Intrinsieke resistentie1

  "valueCodeableConcept": {



    "coding": [ {



      "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",



      "code": "R"



    } ],



        "text" : "Intrinsieke resistentie2"



-> Intrinsieke resistentie2

"valueCodeableConcept": {
"coding": [ {
"system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
"code": "R"
} ]
-> R

**Comment by bdc-ehealth** [comment]
@LotteAd 
Do you want this for all CodeableConcepts, or only for the ones related to micro-biology... I see the example you gave + the one Stefan gave are both strictly related to a micro-biology result. 

It is difficult for us to limit this to microbiology results only, since we have no fixed namingsystem to associate with them. Each lab can provide its own namingsystem here (and justly).

@ec-ehealth : keep this discussion in mind when fixing...

**Comment by LotteAd** [comment]
I think this can be the rule for every example. Showing a code is never a good idea, in my opinion, as this is often unreadable for the person receiving the information.

Van: Bart Decuypere (eHealth) ***@***.***>
Verzonden: woensdag 31 augustus 2022 12:22
Aan: hl7-be/lab ***@***.***>
CC: Lotte Adriaensen ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [hl7-be/lab] Display of text when there is no code display available (Mail de Stefan Waegemans 30/08/2022) (Issue #137)


OPGELET: Deze boodschap komt van een externe partij. Wees steeds voorzichtig bij het openen van bijlagen en links.

@LotteAd<https://github.com/LotteAd>
Do you want this for all CodeableConcepts, or only for the ones related to micro-biology... I see the example you gave + the one Stefan gave are both strictly related to a micro-biology result.

It is difficult for us to limit this to microbiology results only, since we have no fixed namingsystem to associate with them. Each lab can provide its own namingsystem here (and justly).

@ec-ehealth<https://github.com/ec-ehealth> : keep this discussion in mind when fixing...

**Comment by bdc-ehealth** [comment]
@ec-health : link with: https://be-ehealth-standards.atlassian.net/browse/ESI-8

Hello,

Dans le ticket 8, on demande d’éviter d’afficher l’interprétation si elle est égale à la value.
Actuellement, le code est construit de cette façon pour l’affichage de la colonne d’intrepretation :

Si pas de valuecodeableconcept et valuestring : affiche le code d’interpretation
Si valuecodeableconcept présent et différent d’interpretation : affiche le code d’interpretation
Si valuestring présent et différent d’interpretation : affiche le code d’interpretation

Pour rappel, valuecodeableconcept et valuestring ne peuvent être présents en même temps.

Avec l’histoire de Lotte je me demande si je dois venir ajouter des tests et affichages par rapport à l’élément display et text.
De base le visualisateur ne gérait pas ces deux champs pour l’intrepretation mais vu que c’est codeableconcept, il est donc j’imagine possible que ces champs puissent arriver rempli.

Votre avis là-dessus

**Comment by bdc-ehealth** [comment]
@ec-ehealth

Oui, quand on lit la demande de Lotte, et comme en effet, c'est un CodeableConcept, il faut aussi appliquer la règle pour le champ interpretation.
