### ISSUE TITLE
 [FHIR Technical Workshop] - Sending old format and Fhir-messages

### ISSUE THREAD

**Issue by DianaPractimed** [hl7-be/lab#143]
At the start, there will be a period of several months that senders and receivers can/may still send and receive messages in the current format (ex. xml with Medidoc protocol).
When a sender or receiver is ready to send/receive Fhir messages, it can do so.

As a sender, how will we know when we can/may send Fhir-messages to certain receivers?
Will someone notify everyone when their application is able to process Fhir-messages with LOINC-codes?
Can every application owner (ex. CareConnect, MyNexuzHealth,...) provide us with a list of physicians working with their application or do we have to obtain this information from the physicians themselve?
Is it possible to send both during this starting period: the old format and Fhir-message. De receiver can then decide which message it will/can process?

As a receiver, how can we let the sender know when we are ready to process Fhir-messages?
Or is there a possibility that we will receive both messages and that we have to be able to choose which one we can/will process?

Diana Kusters
Head of IT - Practimed

**Comment by bdc-ehealth** [comment]
There will be an infrastructure component available where you can collect all GPs that are able to accept FHIR messages (on the level of chemical analyses and biological analyses). This component still has to be set up (see #93 )

**Comment by bdc-ehealth** [comment]
@DianaPractimed 

Until the availability of the tool in #93, the current system should be used (i.e. each lab system is aware of the format the customer expects, so next to HealthOne, Medidoc, ... also FHIR should be added).
