### ISSUE TITLE
When to use Collection vs. Document?

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#146]
There appears to be two ways to structure the FHIR message: one using a Bundle of type "collection" with as first element a BeLaboratoryReport (aka DiagnosticReport); and another using a Bundle of type "document" with as first element a BeLaboratoryreportComposition (aka Composition).

It's not clear to me when to use the one and when to use the other. Is it sufficient to only support type "collection"?

**Comment by costateixeira** [comment]
https://build.fhir.org/bundle.html#using
https://www.hl7.org/fhir/documents.html

FHIR resources can be used to build documents that represent a composition:
a coherent set of information that is a statement of healthcare
information, including clinical observations and services. A document is an
immutable set of resources with a fixed presentation that is authored
and/or attested by humans, organizations and devices.

A collection is simply a series of 0 or more resources.

**Comment by costateixeira** [comment]
In other words, the Document is used when we want to persist a snapshot of
the information - someone determines that THESE resources form a consistent
and ordered set of information. Typically with an author, a date-time and
even some signature to affirm the integrity.

When the resources are just "bundled" together without concerns of
integrity and immutability of the set, a Collection can be used as well

**Comment by FlorianBonte-Moonchase** [comment]
Thanks. This clears up the confusion. I suppose this interpretation is correct:

- The responsible clinical biologist inspects the complete test results and approves them. The result message is of type "document".
- A result with a severe medical implication is manually sent before other results are known and approved. The result message is of type "collection" as it is an incomplete list of current known values that is expected to be modified in the future.

**Comment by costateixeira** [comment]
Just one precision:

The preliminary or partial results can also be a "draft" document. A
collection is more related to sending "this is a bunch of unordered stuff
that we have right now, and they may change until we have the doctor to
review and select the relevant ones"
