### ISSUE TITLE
Display of special characters (eg. 'µ') goes wrong in visualiser

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#156]
Some test results have an unit that contains a 'µ' character. This is not properly displayed in the visualisation tool (both the one found [here](https://vizapp.icure.dev/) as the one I have built locally).

![afbeelding](https://user-images.githubusercontent.com/101651854/190102439-2f2ba32f-2c2c-4a82-be76-2dfd725cd101.png)

Example problematic message:

[220914103259-T-2209-00027-BeLaboratoryReport-FHIR.zip](https://github.com/hl7-be/lab/files/9564348/220914103259-T-2209-00027-BeLaboratoryReport-FHIR.zip)

Is this purely a visualisation issue, or is the file encoding wrong? Will a GP see the correct symbol?

**Comment by bdc-ehealth** [comment]
@FlorianBonte-Moonchase 
Your file is ANSI encoded. It should be UTF-8 encoded.

This is described in the international standard here: https://www.hl7.org/fhir/json.html .

**Comment by FlorianBonte-Moonchase** [comment]
Sometimes, the solution is obvious. Thanks!
