### ISSUE TITLE
Improve references in Bundle examples

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/lab#158]
The Bundle examples contain incorrect references. For example in Bundle-antibiogramAsBundleCollection the DiagnosticReport.specimen reference is:

```xml
 <specimen>
   <reference value="Specimen/specimen50"/>
 </specimen>
```
Which tries to reference:

```xml
<entry>
    <fullUrl value="urn:uuid:7c16c9c0-c471-4098-ae18-48abcadd8d36"/>
    <resource>
      <Specimen>
        <id value="specimen50"/>
```
------------

Either the reference should be 

```xml
 <specimen     
    <reference value="urn:uuid:7c16c9c0-c471-4098-ae18-48abcadd8d36"/>
  </specimen>
``` 
And the referenced resource.id should match the `.fullUrl`. :

```xml
<entry>
    <fullUrl value="urn:uuid:7c16c9c0-c471-4098-ae18-48abcadd8d36"/>
    <resource>
      <Specimen>
        <id value="7c16c9c0-c471-4098-ae18-48abcadd8d36"/>
```

Or the reference stays as is and the  referenced resource should get an absolute URL in the `.fullUrl`:
```xml
<entry>
    <fullUrl value="https://acme.org/Specimen/specimen50/"/>
    <resource>
      <Specimen>
        <id value="specimen50"/>
```

**Comment by bdc-ehealth** [comment]
@ArdonToonstra : I improved the references in the examples.
