### ISSUE TITLE
Observation.performer in examples

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/lab#159]
The section 3.4.4 states the following:
>The performer of the observation
> The BeObservation.performer field can contain a reference to an external lab, if the test was performed by a subcontracting lab.

The `Observation.performer` in the below-listed examples all refer to a practitioner rather than a lab.

* https://build.fhir.org/ig/hl7-be/lab/Bundle-hematologyStudiesAsFHIRDocument.xml.html
* https://build.fhir.org/ig/hl7-be/lab/Bundle-antibiogramAsBundleNN.xml.html
* https://build.fhir.org/ig/hl7-be/lab/Bundle-antibiogramIsNegativeAsBundleCollection.xml.html
* https://build.fhir.org/ig/hl7-be/lab/Observation-obsCreat.xml.html
* https://build.fhir.org/ig/hl7-be/lab/Observation-obsDynamicHead.xml.html

**Comment by bdc-ehealth** [comment]
The question to be answered here is:
- SHALL the ``Observation.performer`` only contain a reference to an external lab
- maybe it is also possible to add a practitioner or ...

To be discussed in the WG. As far as I recollect, section 3.4.4 was added as a hint to users that they can add subcontracting labs in this way, but it was not the only option to use this field.

**Comment by ArdonToonstra** [comment]
Perhaps this ticket is not really an issue. On second thought, I think the specs are clear on the fact that it may include a practitioner reference for `Observation.performer` as well. 
It would be a small improvement if section 3.4.4. was represented in one or more example(s), but this may not be the most important example to illustrate.

**Comment by bdc-ehealth** [comment]
As there is no problem anymore for Sciensano, we leave it like it is.
