### ISSUE TITLE
BeObservationLaboratory.category 

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/lab#160]
The Dutch profiles for LaboratoryTestResults define a mandatory `.categegory` element containing the FHIR terminology to indicate that the Observation is of the category 'laboratory' like:

```json
{
  "coding": [
    {
      "system": "http://terminology.hl7.org/CodeSystem/observation-category",
      "code": "laboratory"
    }
  ]
}
```
This may be helpful for sorting, indexing, and searching, primarily when multiple use cases are implemented that use the Observation resource. What is HL7 BE's opinion about this?

The Nictiz profiles:
* [Nictiz STU3 profile](https://simplifier.net/NictizSTU3-Zib2017/zib-LaboratoryTestResult-Observation)
* [Nictiz R4 profile in draft](https://simplifier.net/nictiz-r4-zib2020/ziblaboratorytestresult)

**Comment by ArdonToonstra** [comment]
In addition, this category code has also been made mandatory by the US Core profiles: http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition-us-core-observation-lab.html

**Comment by bdc-ehealth** [comment]
At the moment we only have a similar indication on the level of the Composition and the Diagnostic Report.

**Comment by bdc-ehealth** [comment]
The CoW group does not recommended but will not oppose if it is optional.

**Comment by bdc-ehealth** [comment]
WG: for secondary data use, or any other uses, a new format can be created, or the current one can be reused without changes. Other use cases are not blocked by the current situation.
