### ISSUE TITLE
How to handle 1 riviz number linked to multiple (different campus?) labs?

### ISSUE THREAD

**Issue by kjau** [hl7-be/lab#163]
1 riviz number can be linked to multiple labs (different campus?), example: 

https://github.com/hl7-be/lab/blob/master/testing/Macsys/815333041/81365677998_815333041_13.json

Riziv number 81365677998 is linked to different labs?
- Diagnosecentrum D.L.O.
- Centraal Medische Analyse Hasselt
- Centrum Medische Analyse Antwerpen
- Centrum Medische Analyse Herentals

Is this correct or is my lab-configuration wrong?

How can I find the correct lab to register the results for?

**Comment by kjau** [comment]
Is this an important detail to know? (Which campus specifically does the result come from?) Can we (in this example) simply import all results on lab "CMA Herentals"? (And in the same fashion pick 1 lab for all the other riviz numbers where we have multiple labs/campuses registered?)

**Comment by bdc-ehealth** [comment]
Alin Derom:
Concerning 1 RIZIV number with several locations. I suggest using the "acitivity center" number of each loctaion. I don't know if a field is forseen for "activity center"

**Comment by bdc-ehealth** [comment]
Solution provided in #187
