### ISSUE TITLE
How to transmit FHIR labo result documents to eHealth?

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#166]
Moonchase is working on supporting the FHIR protocol for result messages for our software Lab Online. The documentation provided here is quite clear on the content of the message, but we're not sure how to send the document to a recipient via eHealth. Normally, our FHIR communication works with a dedicated FHIR endpoint that has support for resource querying and such (via the HAPI FHIR framework).

I understand eHealth will not work in this way?

I have received some documentation about working with the eHealthBox and it appears it works like this:

do a POST request to: `<platform-url>/mailboxes/{accessKey}/publications`
with as body a JSON that looks like this:

```
{
	"type": "DOCUMENT",
	"title": "report title",
	"recipients":[],
	...
	"payload": {
		<The actual FHIR message>
	}
}
```

Am I on the right track?

**Comment by bdc-ehealth** [comment]
1) I think you are on the right track... Payload, however is a string, and as I understand the documentation, the FHIR document should be escaped and treated as a string value in the payload field. Treating the payload as a JSON-object would be a more elegant option, and I will ask whether this is also supported.

2) Indeed, at the moment, we do not have a regular "FHIR-server" available. We will first put the payload in a FHIR format in the current flows: eHealthBox and Hub/MetaHub system. 

I add a previous information exchange via the eHealth support mailbox here as a reference for other implementers:

```
Hi Florian, you can find the eHbox cookbook here: https://www.ehealth.fgov.be/ehealthplatform/file/view/AW7Wh2x8-O-PGwRRRUGz?filename=eHealthBox_v4_REST_Cookbook_v1.1_05122019.pdf

For testing, we recommend you to get in contact with somebody who has an eHBox (and thus has a RIZIV/INAMI-number). You will be able to send test messages to that person.

If you don’t have someone available, we can work out some other way.

BTW: you could have asked this question on the GitHub as well, it might be useful for other users.

regards,

Bart.
```

**Comment by FlorianBonte-Moonchase** [comment]
Great, thanks for the reassurance!

**Comment by bdc-ehealth** [comment]
@FlorianBonte-Moonchase 
The technical team also indicated that `` POST /mailboxes/{accessKey}/publications`` can also be used as a multipart message, with the json message as an attachment. The serialisation of the JSON is not necessary in that case, but you'll need the construction of a multipart message.
