### ISSUE TITLE
BeServiceRequest

### ISSUE THREAD

**Issue by FlorianBonte-Moonchase** [hl7-be/lab#167]
I see that some examples for an Observation resource (eg. http://build.fhir.org/ig/hl7-be/lab/Bundle-hematologyStudiesAsFHIRDocument.json.html) have a reference to a ServiceRequest in their "basedOn" field. The "profile" field in the "meta" field of that ServiceRequest refers to "https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition/be-servicerequest" suggesting that this is a custom definition, similar to the BeDiagnosticReport and BePatient.

However, I was unable to locate a definition for such a "BeServiceRequest". In the BeObservationLaboratory resource profile, the "basedOn" field refers to a reference which could be of type "ServiceRequest", which is a generic FHIR type.

Is there a specification for the "BeServiceRequest"? Any must-support fields?

**Comment by bdc-ehealth** [comment]
Hi @FlorianBonte-Moonchase ,

At the moment, there is no such definition. The example you indicate is erroneous and should be adapted. There will be a labrequest in the future, see: www.github.com/hl7-be/referral, but this effort has not been completed yet. 

The only requirement in the current profile is for a general "ServiceRequest".
