### ISSUE TITLE
Question about Composition relatesTo

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#179]
I have a question concerning following point in section 3.15.2 of the HL7 BE Laboratory WG Implementation Guide:

_The Composition relatesTo (operationally determined - SHALL be used when needed to express a document replaces a previously created document.). This is found in Composition.relatesTo and when used SHALL take the value 'replaces'. The element Composition.relatesTo.target.targetIdentifier SHALL give the unique document identifier (as described supra) of the other FHIR document.
please note it MAY be possible a FHIR document that was initially marked as 'final' is still followed up later by a new 'final' version. As such implementers SHALL take note whatever status a FHIR document has, it MAY always be replaced._

From my understanding, SHALL is equivalent to "mandatory", am I'm right? If so, do we really want to make the use of relatesTo mandatory in this scenario?

I'm asking this questions for following reasons:

- This rule implies that the sending system must store each bundle identifier it generates in a persistent way each time a new report is sent. This implies some additional complexity and possibly data base changes on sender side.
- In my opinion, the business identifier of the diagnostic report (which must remain the same for different versions of the same report) should be enough for the sender to be able to identify the document to be replaced.
- I had a look on some of the examples in https://github.com/hl7-be/lab/tree/master/testing. I found a lot of example with a 'versionId' > 1 in the meta of the diagnostic report but none of them with something in 'composition.relatesTo'. So, it seems to me that there is an inconsistency between the sample messages from the testing phase and the rules describe in the implementation guide. A'm I right or is my understanding of section 3.15.2 of the IG just wrong or is the IG outdated?

**Comment by bdc-ehealth** [comment]
@frederic-istace 

Hi Frédéric,

your observation is correct. The document states that Composition.relatesTo should contain the document id  (i.e. the bundle id) of the document it refers to. This makes sure that a document with the same composition identifier (or diagnostic report identifier, which is identical) cannot be replaced by an earlier version, and only by a version that is referring to it. This can be done in different ways (e.g. by using the creation date of the bundle).

If you want to change this requirement, we should bring it forward to the HL7 lab group. Please let me know if you want to be invited.

**Comment by frederic-istace** [comment]
Hi Bart,

Thank you. I already participated to some of the meetings from the group (last time on 2022-10-25) but didn't receive any invitations recently. Are there still WG meetings planed in future?

Best regards,
Frédéric

**Comment by daanw-cegeka** [comment]
Hi all,

I also would like to have this requirement relaxed because it adds complexity for the sender. (I work on the senders side) If my presence is required to make this change in the requirements, you can invite me (daan.wendelen@cegeka.com).

Maybe none of the receivers will use `Composition.relatesTo` because it is a brittle mechanism. It's brittle because messages could arrive out-of-order and if one message in the chain is missing, the whole chain is broken. Maybe those problems could be mitigated but that also adds complexity and I do not know how to make this airtight.

A simple and very robust solution for the older-version-problem is that we uses some field that is always higher for a newer version. eg incremental version numbers, timestamps, ... 

Regards,
Daan

**Comment by bdc-ehealth** [comment]
COW: we propose to adapt the text in the IG, and remove the section on relatesTo. The profile will be adapted if necessary.

**Comment by AlexisVZ-MDS** [comment]
@bdc-ehealth And thus we use the "issued" timestamp to sort the the versions and identify the latest ?

**Comment by kjau** [comment]
@AlexisVZ-MDS: there is a chapter in the guidance about versioning: https://ehealth.fgov.be/standards/fhir/lab/guidance.html#Versioning%20of%20reports
=> use the versionId field in the "Meta" of the DiagnosticReport to determine the ordering of the received reports. See also the testing examples of MacSys and MIPS, example => https://github.com/hl7-be/lab/blob/master/testing/Macsys/815333041/81365677998_815333041_13.json
