### ISSUE TITLE
Update examples in accordance with decision in #105

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/lab#183]
The workgroup decides to wait for additional testing at Gent and Charleroi.

The SNOMED-CT issue is followed up by Philippe Cauchie and Tom Fiers.

We will use the CodeableConcept to indicate RIS. For the RIS specific LOINC code we put it in both the value and the interpretation.

_Originally posted by @bdc-ehealth in https://github.com/hl7-be/lab/issues/105#issuecomment-1068163733_

The usage of Observation.valueCodeableConcept for RIS has not yet made it to the examples in the repo. This should be improved?

**Comment by bdc-ehealth** [comment]
@ArdonToonstra This only applies if there is no other value  apart from the interpretation. Is that what you understood as well?

**Comment by ArdonToonstra** [comment]
@bdc-ehealth, I interpreted  "_For the RIS specific LOINC code we put it in both the value and the interpretation_." as that you would use both `.valueCodeableConcept` and `.interpretation` for RIS observations. 

I would expect that you primarily use the `.value[x]` for the result of the lab test, which in this case would be the RIS value. The `.interpretation` information says something about the observation value. To me, it is odd that you would have an interpretation but not a result.

**Comment by bdc-ehealth** [comment]
@ArdonToonstra During the discussions in the workgroup, it appeared to be possible that for some tests, there is only an interpretation available (i.e. if there is no quantitative result of a test, but only a qualitative one). In that case, the RIS code will be present in both interpretation and value.

**Comment by ArdonToonstra** [comment]
@bdc-ehealth , in this example https://build.fhir.org/ig/hl7-be/lab/Bundle-antibiogramAsBundleNN.json.html,

should for example the Observation with id = 'org51-trimethoprim-sulfamethoxazole' be updated from 

```json
        "performer" : [
          {
            "reference" : "urn:uuid:7c16c9c0-c471-4098-ae18-48abcadd8d73"
          }
        ],
        "interpretation" : [
          {
            "coding" : [
              {
                "system" : "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                "code" : "S",
                "display" : "Susceptible"
              }
            ]
          }
```

to 

```json
  "performer":  [
                    {
                        "reference": "urn:uuid:7c16c9c0-c471-4098-ae18-48abcadd8d73"
                    }
                ],
                "valueCodeableConcept": {
                    "coding":  [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                            "code": "S",
                            "display": "Susceptible"
                        }
                    ]
                },
                "interpretation":  [
                    {
                        "coding":  [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                                "code": "S",
                                "display": "Susceptible"
                            }
                        ]
                    }
```

Or do I misunderstand the situation somehow?

**Comment by bdc-ehealth** [comment]
No, you are right. We will take care of it.

**Comment by ArdonToonstra** [comment]
Great! I imagine that fixing the examples is not a top priority. But It is also good to know we are on the same page.

**Comment by ArdonToonstra** [comment]
@bdc-ehealth , nice work. I checked the example and looks good.
