### ISSUE TITLE
How to put many labreports in one file

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#184]
There are multiple ways to send multiple reports using the eHBox. You can attach multiple annexes to one eHBox message. It is also possible to put many reports in one "Bundle", and that bundle is one file. There are some points of attention on how to do this.

1) According to the "Document" rules of FHIR, there can only be one Composition in one Document Bundle (http://hl7.org/fhir/documents.html). Because there are some rules for replacement attached to the Composition status, the Composition can only be valid for one labreport (Diagnostic Report). So the Bundle type for multiple reports cannot be of type "document"

2) By definition, we cannot use the Transaction(Response), Batch(Response) , History, Message or SearchSet types of Bundle

The only option left is a Bundle of type 'collection'

**Comment by pablocorilus** [comment]
@bdc-ehealth If the question has already been answered somewhere else i'm sorry. I'm trying to get though all te past comment.
As I understood it from my colleague, the idea was to have one bundle per patient. Is this assumption still correct.

**Comment by bdc-ehealth** [comment]
@pablocorilus : You can see the example here: It is in fact a bundle of bundles if you want to have more than 1 patient in one file/eHealthBox attachment, because of the reasons indicated above: You can see an example here: https://raw.githubusercontent.com/hl7-be/lab/master/testing/eHealth/Bundle-bundle-2-reports-2-patients.json. If you only have 1 patient, one bundle is enough. Please keep in mind that it is also possible to have multiple eHealthBox attachments, each containing one bundle for one patient.

**Comment by pablocorilus** [comment]
@bdc-ehealth So the assumption that one bundle equals one patient, on the lowest level is good from our side. 
But here is a challenge that we have as a GP,  does the concept of bundle of bundles mean that one eHealthBox messages can be about multiple patients. As we understood in the beginnen of labo fhir that was not expected to be the case anymore.
One of the challenges is the splitting at our side, so the quicker i know about it the better.

**Comment by bdc-ehealth** [comment]
@pablocorilus : indeed, there was an explicit request from the labs that one eHealthBox message should be able to contain more than one patient. There are two ways to accomplish this: 1 patient per eHBox attachment, or 1 eHBox attachment with a Bundle of Bundles. So in the general case, each eHBox attachment can contain either a simple bundle of type document, for 1 patient, or a bundle (of type 'collection') of bundles of type 'document', each bundle of type 'document' containing information for 1 patient.

**Comment by bdc-ehealth** [comment]
COW: find out who was the original asker, and invite him for the next meeting.

**Comment by bdc-ehealth** [comment]
The original asker of the question was: @Rogister

Alain, could you please explain in which circumstances you will use a file with multiple patients for one GP?

**Comment by Rogister** [comment]
Pour les questions sur les fichiers labo, je te mets en contact directement avec mon collègue Nicolas Robert.

Il a fait le développement et déjà traité ce cas.

De : Bart Decuypere (eHealth) ***@***.***>
Date : mercredi, 8 mars 2023 à 13:47
À : hl7-be/lab ***@***.***>
Cc : Rogister Alain ***@***.***>, Mention ***@***.***>
Objet : Re: [hl7-be/lab] How to put many labreports in one file (Issue #184)

The original asker of the question was: @Rogister<https://github.com/Rogister>

Alain, could you please explain in which circumstances you will use a file with multiple patients for one GP?

**Comment by bdc-ehealth** [comment]
COW: we propose not to allow this way of working, because it is rare and is not used by any of the participants in this meeting.

**Comment by bdc-ehealth** [comment]
@sttav Indeed, the visualizer does not support it. It is however a valid FHIR construction (you can use the public domain FHIR validator to prove that: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator ). As you can see above, the design group of the profile does not like this solution, and we may actively discourage its use, if the full HL7 Belgium workgroup agrees.

**Comment by Rogister** [comment]
Bonjour,

De notre côté, nous avons fait le développement pour accepter les fichiers FHIR contenant plusieurs patients. Donc si vous décidez que 1 fichier = 1 patient ou que 1 fichier = plusieurs patients, c’est la même chose pour nous.

Ce qu’il faut savoir, c’est que pour le moment, on reçoit des fichiers qui contiennent plusieurs patients donc il faut voir cela directement avec les laboratoires.

Alain Rogister
Responsable Informatique OffiMED
Logiciel : Medinect

De : Bart Decuypere (eHealth) ***@***.***>
Date : mercredi, 29 mars 2023 à 13:48
À : hl7-be/lab ***@***.***>
Cc : Rogister Alain ***@***.***>, Mention ***@***.***>
Objet : Re: [hl7-be/lab] How to put many labreports in one file (Issue #184)

@sttav<https://github.com/sttav> Indeed, the visualizer does not support it. It is however a valid FHIR construction (you can use the public domain FHIR validator to prove that: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator ). As you can see above, the design group of the profile does not like this solution, and we may actively discourage its use, if the full HL7 Belgium workgroup agrees.

**Comment by bdc-ehealth** [comment]
@Rogister Thanks for your answer!

**Comment by sttav** [comment]
Dear all,
indeed, for us as a lab, we select all patients per doctor and send all those reports in 1 file to the doctor = recipient.
This is what was possible in all previous formats like Medidoc, Medar...   so why not in FHIR ?
As you say, the standard allows it.

**Comment by KristiaanJaques** [comment]
It is essential to be able to provide a single result file containing multiple reports. In a full fledged system this flexibility in functionality needs to be available. More so since the international standard evidently has implemented this feature.

**Comment by sttav** [comment]
Dear all,
We have an absolute need to be able to put more than one patient report in one file. It is not only logical because the international standard has implemented this, but also because it makes the structure more versatile and usable, less constrained. Regularly we get the request to resend many hundreds, even thousands of reports to the same address. The logic is to have the reports contained in the same file, not in a multiple of files. We do not want to lose this possibility just because it was overlooked initially when the Belgian version of FHIR was contemplated on.

**Comment by bdc-ehealth** [comment]
@KristiaanJaques @sttav There has not been any official HL7 Belgium Lab Meeting regarding this topic. This means that this feature is still not forbidden, and the need for it, and the use of it by you will certainly be taken into account. You can still use this feature.

**Comment by FrederikVds** [comment]
Hi, @bdc-ehealth ,

Is there a way for us to upload these to the test server so software vendors that receive FHIR reports can check whether or not they correctly support these?

**Comment by pablocorilus** [comment]
@bdc-ehealth , I second the request of Frederik

**Comment by bdc-ehealth** [comment]
@FrederikVds , @pablocorilus ,

we see that these questions keep coming back, and we will introduce a feature to support this. As we see it now, an incoming bundle of bundles will be separated in its constituents, and each constituent will be processed separately. Secondly, it will be able to choose a set of reports using a checkbox per report, and you will have a button to send the bundle of bundles to the eHealthBox. 

Is that sufficient for you?

**Comment by FrederikVds** [comment]
Hi @bdc-ehealth ,

That would be great for us, thanks!

**Comment by pablocorilus** [comment]
@bdc-ehealth thanks
