### ISSUE TITLE
Resource.id management

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#187]
Hi,

Are there any rules on the Resource.id fields? I cannot check the IG right now (the link http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/ is down).

For the DEMIS project in Germany, they proposed using UUIDv5 with a unique labcode as namespace. This makes every resource unique. At some point in the future, this would even allow for lifecycle management of the resources.

What does the group think? Is this something we should also start doing?
What would you use as the unique labcode? I suggest the RIZIV/INAMI number of the lab that is used in the diagnosticReport.identifier.

Best,
Thibault

**Comment by bdc-ehealth** [comment]
@thibaultmh : the url of the build server has changed since at least Aug 31, 2022. Now it is: http://build.fhir.org/ig/hl7-be/lab

**Comment by bdc-ehealth** [comment]
linked to #18 and #163:

I sent a mail to the biologists:
Hello,

During the meeting of the COW FHIR Lab results, there was a question that originated at UZLeuven, but that could impact the way we assign IDs to our lab reports.

This is the problem:

If there is a lab in Belgium, (with one RIZIV/INAMI number) with 2 or more campuses, and at least one of those campuses has a separate Lab system that provides its own report IDs, then we might have duplicates.

Example:

LAB A CAMPUS A creates in its system reportID (convention in the standard: RIZIV number + internal report number) 83660619.1

If LAB A CAMPUS B has a different system, it can according to this convention also create 83660619.1

Question:

Are there in Belgium labs that have 
1)	Different campuses with the same RIZIV/INAMI number?
2)	And have on those campuses separate LIS systems that can create the same internal report number?



In the discussion in https://github.com/hl7-be/lab/issues/18 we assumed that the LAB (identified by the RIZIV/INAMI-number) would be responsible for the uniqueness of its report IDs. Do we maintain this position?

**Comment by alinderom** [comment]
Hello,
The first question is : Is this an existing situation in Belgium? I do not think so.
Every lab has it’s INAMI number.
Every lab has a software for its activities (LIS). Although 1 LIS can be used by several labs with each their own INAMI number
I have no knowledge of a lab with 1 INAMI number that used 2 unsynchronized/unrelated LIS systems that each produce their own overlapping report IDs that could not be distinguished.
So I do think the question is irrelevant.

However Every lab should a a standard procedure be sure that all the reports of different prescriptions can be identified independently within the lab (where “lab” means 1 INAMI number).
So with the combination INAMInumber +  report-number we have a unique identifier.

However : no lab has unique number till eternity. We should agree upon a time period where the combination INAMI+reportID should be unique. I don’t remember if this has been discussed, but I suggest the report-numbers are (in a worst case scenario) unique for at least a decennium, and preferably a century. 
Eventually the use of “sampling date can be added” as a unique maker on the side of the receiver with keeping in mind that all samplings are not always done within 1 calendric day. A lab can however never rely on the sampling date to make their reportID unique in a period of 1 century.

Attention : I am talking about a unique ID of "a report of 1 prescription", this answer says nothing about a unique ID of the same report that have been reported several times. (incomplete 1, incomplete 2,, final report)

**Comment by bdc-ehealth** [comment]
COW: we stick to the current situation based on the information provided by A. Derom.
