### ISSUE TITLE
visualization tool is not working

### ISSUE THREAD

**Issue by pvandecandelaere** [hl7-be/lab#188]
Dear
Today we cannot upload json files in the visualization tool 
https://vizapp.icure.dev/

on 2/2/2023 it worked, today it does not work.

can you have look what could be the problem ?
best regards
Patricia Vandecandelaere

**Comment by bdc-ehealth** [comment]
@pvandecandelaere ,

We are changing the hosting of the tool, and apparently, there is a problem. We are looking into it.

Sorry for the inconvenience.

**Comment by bdc-ehealth** [comment]
@pvandecandelaere : the migrated version of the tool is available at: https://fhir-testserver.be/index.php/visualization_webapp
