### ISSUE TITLE
Result - External comment

### ISSUE THREAD

**Issue by pvandecandelaere** [hl7-be/lab#189]
Dear
We don't see any result - external comments in the Fhir report.
What is the reason for that ?

best regards
Patricia

**Comment by bdc-ehealth** [comment]
@pvandecandelaere 
if you send your file(s) to support@be-ehealth-standards.atlassian.net or paste them here, I will take a look at them.

**Comment by pvandecandelaere** [comment]
OK, zie mijn mail aub
mvg, 
Patricia

**Comment by bdc-ehealth** [comment]
@pvandecandelaere : the version of the standard you are using has been officially replaced since 08/09/2022, please use the official version of the standard https://www.ehealth.fgov.be/standards/fhir/lab/index.html .
