### ISSUE TITLE
Micro-organisme external comment

### ISSUE THREAD

**Issue by pvandecandelaere** [hl7-be/lab#190]
Dear
We don't see any micro-organism external comment in the Fhir report.
What can be the reason for that please ?

best regards
Patricia Vandecandelaere

**Comment by bdc-ehealth** [comment]
@pvandecandelaere : the version of the standard you are using has been officially replaced since 08/09/2022, please use the official version of the standard https://www.ehealth.fgov.be/standards/fhir/lab/index.html .
