### ISSUE TITLE
Visualisation tool

### ISSUE THREAD

**Issue by RDEVIDTS** [hl7-be/lab#193]
Could it be that the visualization tool has recently stopped working? My files were always correctly processed by the tool until recently. Now I keep getting an error (see attachment)

Rinaldo
[error.pdf](https://github.com/hl7-be/lab/files/10978360/error.pdf)

**Comment by bdc-ehealth** [comment]
@RDEVIDTS : there is a new URL for the visualization tool, because it is now hosted elsewhere. We published the new location here: https://github.com/hl7-be/lab#faq
