### ISSUE TITLE
May url references to identifier systems be empty or dummy

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#20]
In the examples we see references to urls of systems of identifiers.  E.g. for order number in ServiceRequest, a url like https://www.medina.be/ServiceRequest might figure.  The problem is that a) Macsys/Medina/CMA/AKL/LKO does not have such URLs, and for security reaons we will never create such (public) url.  May this be empty, or may this be populated by dummy (non-existing) urls?

**Comment by costateixeira** [comment]
Those are NamingSystems which we can perhaps add to our specifications.
NamingSystems do not have to resolve. The URLs act as a unique, permanent identifier, which is critical so we should try to get it right from the beginning.

**Comment by bdc-ehealth** [comment]
WG The URL does not need to resolve, but it should remain stable over time. We do not list all NamingSystems in the standard. The URL cannot be empty.
