### ISSUE TITLE
REST API usage for testing

### ISSUE THREAD

**Issue by sebwautelet** [hl7-be/lab#200]
Hello,

I got access to the test server but I can't find any documentation about how to use the REST API for testing.
I tried sending a FHIR bundle as the POST request body to the given URL, but I get an HTTP 500 error.

```
POST /index.php/fhir/###/lab/R4/bundle?api_key=### HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: application/fhir+json
Content-Length: 110611
Host: fhir-testserver.be
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.5 (Java/16.0.1)

{
  "resourceType" : "Bundle",
  ......
}
```

Can you tell me what I'm doing wrong or point me to more documentation about this API?
Thanks

**Comment by bdc-ehealth** [comment]
@sebwautelet ,

We are working on some more detailed information (@jmp-ehealth), but I will share some requests that I made using Postman. The API is accessible, other stakeholders have been using it (see: https://github.com/hl7-be/lab/issues/198)
![image](https://github.com/hl7-be/lab/assets/90335317/a00c30b8-41f3-4c6c-91c5-2726722ec71b)
![image](https://github.com/hl7-be/lab/assets/90335317/2117d5d2-aa7d-46b3-a3ad-ae61d942d8f5)
![image](https://github.com/hl7-be/lab/assets/90335317/85c1ddec-0e77-4240-8e98-33fe05b05e27)

If you still have problems, you can send me your unobfuscated URL  to support@be-ehealth-standards.atlassian.net and I will check your data.

**Comment by sebwautelet** [comment]
Thanks @bdc-ehealth , I managed to make it work with Postman. My first try was with SoapUI, not sure why it was not working as the headers look the same.
