### ISSUE TITLE
Error vizualisation tool

### ISSUE THREAD

**Issue by RDEVIDTS** [hl7-be/lab#202]
Best,
Since today I get an error 500 when uploading files to the visualization tool.
Thanks
[Error vizualisation tool.PDF](https://github.com/hl7-be/lab/files/11878539/Error.vizualisation.tool.PDF)

**Comment by bdc-ehealth** [comment]
@RDEVIDTS 

The error is caused by an external service. In the meantime the external service is up again. Sorry for the inconvenience.

**Comment by bdc-ehealth** [comment]
@RDEVIDTS 
For me, it is working:
![image](https://github.com/hl7-be/lab/assets/90335317/73f651b3-5ed8-4c3f-8e16-4b4029ed2a9c)
Are you behind a proxy?

**Comment by RDEVIDTS** [comment]
No, I'amnot
[2023-06-27_130840.PDF](https://github.com/hl7-be/lab/files/11881259/2023-06-27_130840.PDF)
 behind a proxy server. I get the same error on my personal PC. 
The tool has always worked well until yesterday.
May I send you a .json file of mine for testing?

[fout.PDF](https://github.com/hl7-be/lab/files/11881266/fout.PDF)

**Comment by RDEVIDTS** [comment]
Note, when i put off 'validation' it works.

**Comment by bdc-ehealth** [comment]
Ah OK, the validition is not working for the moment (there is a notice at the top).

**Comment by bdc-ehealth** [comment]
@RDEVIDTS The validation is available again. All should be well!
