### ISSUE TITLE
Issue with test case 5B

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#212]
Could you please check why our test result under ID 118 for test case 5B is marked as failed? Looking at the JSON, it seems to me that the observation is correctly linked to the specimen.

So, I don't understand the diff result:

{
[fhirpath](https://fhir-testserver.be/index.php/user/secured/messages/index): [
{
actual: false,
field: "Bundle.entry.where(resource is Specimen).fullUrl.select($this.toString()) in Bundle.entry.where(resource is Observation).resource.specimen.reference",
expected: true
},
{
actual: false,
field: "Bundle.entry.where(resource is Observation).resource.specimen.reference in Bundle.entry.where(resource is Specimen).fullUrl.select($this.toString())",
expected: true
}
]
}

Is it a problem in the condition or am I overlooking something?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

you are right, the condition did not take URNs into account. I changed the condition, but there appears to be yet another problem. Outside of the testserver, your file is accepted with the current condition, but in the testserver, it still fails. We will investigate.

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Thanks. I think there is a similar issue with test case 5. See test result 120 for message ID 643.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

To cut a long story short, I solved the issue for 5B and 5, and I have re-evaluated your messages, which are green now.
