### ISSUE TITLE
Question about test cases 9A1 and 9A2

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#213]
The reference file for test case 9A1 contains an observation identified with the LOINC code 630-4 "Bacteria identified in Urine by Culture" and resulted with "Negatief (geen groei)" as well as an observation identified with the LOINC code 29576-6 "Bacterial susceptibility panel" resulted with "Niet uitgevoerd".

This situation is not really applicable to our system because an antibiogram is only performed when the culture test is positive and a antbiogram battery is never order as a standalone test without culture test. So, if the result of the culture is negative, we will never print any information about an antibiogram related to this culture on the paper report. 

In my opinion, the presence of LOINC code 29576-6 in this test case is something which is specific to the system which has produced the reference file. Therefore, I would suggest to suppress the test assertion on LOINC code 29576-6 for this test case.

Furthermore, I think for the same reasons that the test case 9A2 should only check the presence of the LOINC code 630-4 which identifies the culture as well as LOINC codes associated to the individual antiobiotics (18862-3, 18906-8, 18955-5...) but that the presence of LOINC code 29576-6 "Bacterial susceptibility panel" should not be considered as mandatory by this test case.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

thanks Frederic, for your remark. I will discuss this with our biologists! I do not have sufficient medical knowledge to judge about that! I will keep you up to date.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

Frederic, in case of a negative test, your approach is approved by the biologists. However to check the structure of the antibiogram, we would like you to send a positive case for this test.

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Please have a look at message 740 related to test case 9A2 for an example of a positive culture result

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

Your structure differs slightly from the MACSYS structure, but this does not impact comprehensibility, so I changed the rule to also allow your structure. 9A2 is now green.

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Could you please also have at look at message 849 related to test case 9A1 which is failing for a similar reason?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,
Indeed, same reason, 9A1 is now green.
