### ISSUE TITLE
FHIR homologation server not accepting new files

### ISSUE THREAD

**Issue by KristiaanJaques** [hl7-be/lab#217]
![Capture](https://github.com/hl7-be/lab/assets/120572072/6bdb4c60-df15-4385-936f-cb40c2e2b8fe)
The FHIR test server seems to be unable to perform interpretation of new test messages today.
https://fhir-testserver.be/index.php/login

**Comment by bdc-ehealth** [comment]
@KristiaanJaques We are checking this...

**Comment by bdc-ehealth** [comment]
@KristiaanJaques The server is up and running again.
