### ISSUE TITLE
Test case 45 - Comments on level DiagnosticReport

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#219]
There is no reference file available yet for test case 45 "Comments on level DiagnosticReport" and I'm wondering in which field the comment should be written? If the Belgian profile would be based on the latestet FHIR version 6.0.0 http://build.fhir.org/diagnosticreport.html, I would include it as a note but there is no note field foreseen in FHIR version 4.0.1 on which the Belgian profile https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition-be-laboratory-report.html is based.

So, should we use the field "conclusion" for it? If so, I think the test case 45 should be relabeled as ' Clinical conclusion (interpretation) on level DiagnosticReport' which is more precise than the generic word 'Comments' which can mean +/- everything.

Furthermore, as I already mentioned in https://github.com/hl7-be/lab/issues/216, it's also possible to send report comments via an observation with the LOINC code 86468-6 'Report comment section' like in test case 41C. So, I'm wondering if test case 45 really makes sense and should not just be dropped from the test plan?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

There is an extension added to the profile (see screenshot):
![image](https://github.com/hl7-be/lab/assets/90335317/06989afa-dec2-48a8-91be-eead20a4a443)

So you can definitely use this extension to put a report level note. The use of an observation with 86468-6 is possible as well.

Both can be used and will be approved. You can be the first to send the reference file ;) !

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Thanks but I don't see a corresponding definition on https://www.ehealth.fgov.be/standards/fhir/lab/1.0.0/artifacts.html#structures-extension-definitions

Should I just invent a new code, like for example 'be-report-comment'?

**Comment by bdc-ehealth** [comment]
@frederic-istace 

https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition-be-ext-note.html

**Comment by frederic-istace** [comment]
@bdc-ehealth 
I have submitted an example using extension be-ext-node for test case 45 under message ID 1656. Could you please have a look at it?

**Comment by frederic-istace** [comment]
@bdc-ehealth 
If fixed it. See message ID 1670.

**Comment by bdc-ehealth** [comment]
@frederic-istace 

test is green.
