### ISSUE TITLE
Test case 5A "Specimen identifiers with LOINC encoding of specimen type" unclear

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#220]
I would like to produce a reference file for test case 5A "Specimen identifiers with LOINC encoding of specimen type" but I'm not aware of LOINC codes for specimen types. From my understanding, a LOINC code may include the specimen type (called "System" in LOINC) but only in combination with other properties (analyte, property, property, time, method, scale). So, I would say the LOINC is suitable to identify the type of an observation resource but not for a specimen resource.

Furthermore, when I look at the sample file https://github.com/hl7-be/lab/tree/master/testing/Macsys/815333044 from Macsys, the specimen type is identified with codes from the coding system 'https://terminology.hl7.org/5.2.0/CodeSystem-v2-0487.html'. This coding system has nothing to do with LOINC.

So, does it mean that the case is miss labelled and should be renamed to something like "Specimen identifiers with HL7 encoding of specimen type" or "Specimen identifiers with local encoding of specimen type"?

I would also like to point out that this test case is in contradiction with the general test strategy documentation https://fhir-testserver.be/files/DIGIRELAB_TestStrategy_FR.pdf which claims that all specimen types must be encoded with SNOMED.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

you are correct. The pdf is wrong. See my comment to your issue https://github.com/hl7-be/lab/issues/208 .

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

I interpret this testcase as follows: use LOINC codes for the observations that contain the Specimen type in their definition: I add an example:

![image](https://github.com/hl7-be/lab/assets/90335317/76cf0a56-e418-44fc-8e5d-5212a1d44e5d)

If a specimen is linked to the observation, it should be of the same type as the type in the definition of the LOINC code. If you think that this interpretation is not correct, I will verify this with our biologists...

**Comment by frederic-istace** [comment]
@bdc-ehealth 
I have submitted a message for test case 5A under message ID 1659. Could you please have a look?

**Comment by bdc-ehealth** [comment]
@frederic-istace 
The test is green.
