### ISSUE TITLE
Question about test case 8E "annex on observation level"

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#223]
I would like to produce a reference file for test case 8E "annex on observation level" but looking at http://build.fhir.org/ig/hl7-be/lab/StructureDefinition-be-observation-laboratory.html, it's not clear to me how base64 encoded data can be embedded in an observation? Are we supposed to use an extension for this?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

see: https://github.com/hl7-be/lab/issues/125 (you can use a Media resource without profile added to the bundle). Put a reference in Observation.derivedFrom.
If you want, you can also add a link here: http://hl7.org/fhir/R4/diagnosticreport.html#:~:text=e.g.%20explanation)-,link,-%CE%A3

**Comment by frederic-istace** [comment]
@bdc-ehealth 
Could you please have a look at message 1708 I have sent for this test case?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

looks good. I will add it tomorrow, I have to leave now.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

your test is green! Thanks!
