### ISSUE TITLE
No visualization for testcase 2F1

### ISSUE THREAD

**Issue by ValerieNexuz** [hl7-be/lab#238]
No visualization is shown after clicking on the visualize button for testcase 2F1. Is this a bug?

**Comment by bdc-ehealth** [comment]
@ValerieNexuz ,

what is the id number of the message? Or do you mean the reference file for 2F1?

**Comment by ValerieNexuz** [comment]
The ID of the testcase is 207. The green button in the picture doesn't work: 
![image](https://github.com/hl7-be/lab/assets/148340478/725f03a7-e5c9-4d4a-8339-f2cdf06aac68)

**Comment by bdc-ehealth** [comment]
@ValerieNexuz ,

There was an error in this reference file. The creator of the reference file already provided a new corrected version, and we put it in place.
