### ISSUE TITLE
Results in different units

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#24]
We often need to report 1 result in more than one unit on the same report.   (e.g. hemoglobine in mmol/L en g/dL).

How do we do this? 

Proposal: we send this as 2 different observations, but both with the same LOINC code, but with different usings and different reference ranges.  That does mean the same LOINC code is use twice in one report.  Is this OK?  If not, how else? Shall we standardise this?

**Comment by alinderom** [comment]
LOINC has separate codes for mmol/L and g/dL, I do propose that the appropiate LOINC code is used, and that we do not use the same LOINC code for both units. eg cholesterol in mg/dL = 2093-3 & in mmol/L = 14647-2

**Comment by bdc-ehealth** [comment]
A discuter si on continue à  l'autoriser car il sera difficile de faire la distinction entre les 2 méthodes.  Un commentaire spécifique peut aider. 



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
Objet : RE: GITHUB - analyse in massa-eenheid en molaire eenheid 

Ik heb in het recente verleden twee gevallen meegemaakt waarbij me gevraagd werd om tijdelijk, voor één parameter, twee resultaten te rapporteren, met identieke eenheid en LOINC. Dit was telkens omwille van het verhuizen van deze parameter naar een nieuw toestel.
 
Onderwerp: RE: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Je confirme 
 
Pour LOINC, une même analyse répondues dans 2 système de concentration différents (on parle de « dimension » ) sont des paramètres indépendants (leurs calibrateurs peuvent avoir des standardisations différentes)
En effet, cette réponse dans deux dimensions différentes est surtout apparue avec la parutions des unités préférentielles où certains paramètres ont changé de dimension. Certains ont eu du mal et demandent toujours la réponse dans l’ancienne unités 
 
Pour un doublon avec changement de méthode, on a deux codes LOINC différents dans la plupart des cas  
Le doublon pour changement d’appareil avec la même méthode  est par contre un jumeau parfait, mais certains paramètres  (surtout en sérologie infectieuse) disposent d’une « 2e méthode »  
 
Sincèrement, Philippe 
 
Dr Philippe CAUCHIE
CHU de Charleroi
 
Objet : Re: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Beste Joris, als reactie op uw laatste bullet point volgende: er bestaat een geldige en eenvoudige manier in FHIR om voor dezelfde test 2 resultaten door te sturen (in g en mml) - aangezien rapportages in gram en millimil verschillende LOINC codes hebben ziet FHIR deze als "aparte analyzen".  Of we onder ons beslissen dat we dat willen doen is een andere zaak natuurlijk.  Maar technisch kan het perfect.
 
Verder als antwoord op uw bedenking "  toegelaten maar enkel indien beide resultaten niet converteerbaar zijn (bv. er is geen norm voor het moleculair gewicht) " : er is altijd een "norm" voor molgewicht (molaire massa) - ik zet "norm" tussen aanhalingstekens omdat dit strikt gezien geen "norm" is, maar een natuurkundig/scheikundig feit. Elke stof heeft een molaire massa, dat is het gewicht van +/-6*10^23 molecules en over die massa valt niet te discussieren hoor 🙂.   
 
Vriendelijke groeten,
 
Tom Tollenaere 
 
 
CIO MacSys
 
________________________________________
Subject: RE: GITHUB - analyse in massa-eenheid en molaire eenheid 
 
	OPGELET: Deze boodschap komt van een externe partij. Wees steeds voorzichtig bij het openen van bijlagen en links. 
Even mijn 2 cent toevoegen aan deze discussie, en een poging om ze ook in een iets breder kader stellen.
 
Het doel van de oefening is het opstellen van een standaard voor een gestructureerd en gecodeerd labo verslag.  We moeten dus regels verzinnen die beschrijven wat volgens deze standaard een geldig document is.  Uit deze regels kunnen we soms een aantal vereisten afleiden voor de producent van zo een document.  We kunnen ook bijkomend adviezen formuleren voor het zinvol gebruik van het mechanisme, maar dat die adviezen kunnen niet als normerend beschouwd worden (voor deze standaard). Dit lijkt vanzelfsprekend, maar ik heb de indruk dat dit in het heetst van de strijd soms uit het oog verloren wordt. 
 
De discussie gaat essentieel over “is het toegelaten de het resultaat van een bepaling twee maal op te nemen in één verslag”.  De concrete situatie waarmee de discussie begon (indien ik me nog goed herinner, lang weekend er tussen), was een verslag met het resultaat van een bepaling in een massa-eenheid, en een tweede resultaat voor dezelfde bepaling in een molaire eenheid.  Maar in principe kan dit ook voor twee verschillende massa eenheden. En als je extreem wil gaan: voor twee keer dezelfde eenheid, maar dan wellicht uitgevoerd met twee verschillende toestellen/methoden.  
 
Afgeleid kan je drie aparte vragen stellen:
 
•        onder welke omstandigheden mag een labo-systeem een verslag aanmaken met daarin twee resultaten voor één bepaling
•        hoe mag een ontvanger systeem een verslag aanmaken met daarin twee resultaten voor één bepaling 
•        wanneer is het zinvol of aangeraden dat een labo-systeem een verslag aanmaakt met daarin twee resultaten voor één bepaling?
 
Maar eerst een paar woorden over de conversie van eenheden.
 
Zoals reeds opgemerkt door Philippe : we gebruiken gecodeerde UCUM eenheden. Dit laat ons toe om omrekeningen te doen. Dit soort omrekeningen zijn zeer eenvoudig wanneer beide eenheden tot dezelfde “familie” behoren. Het is niet moeilijker dan een omrekening van km/h naar m/s.  Indien je jezelf software ingenieur/developer/… noemt en hier niet in slaagt, lijkt me een bezinning over je carrièrekeuze aangeraden. We vergeten natuurlijk niet dat we ook moeten nadenken over de significante decimalen van de omgerekende waarde.
 
Een omrekening tussen een massa-eenheid en een molaire eenheid is minder evident omdat we hier het moleculair gewicht van de betrokken stof moeten kennen.  Voor vele eenvoudige stoffen is die makkelijk te achterhalen, voor bepaalde macro-moleculen bestaat die gewoonweg niet maar zal de vraag zich ook nooit stellen.
 
Indien we op zinvolle wijze een norm of zelfs advies willen opstellen m.b.t. dit soort omrekeningen, moeten we kunnen refereren naar een tabel waarin deze moleculaire gewichten opgesomd staan, per parameter.  Concreet stel ik me een tabel voor met 3 kolommen : LOINC voor de parameter in massa-eenheden, LOINC voor de parameter in molaire eenheden, moleculair gewicht.  Dit zou een nuttige aanvulling kunnen zijn van onze ReTaM, ik weet niet of dit tot onze ambities hoort.
 
Over tot de essentie
 
De eerste vraag: mag een labo-systeem twee resultaten voor éénzelfde bepaling opnemen in één verslag? 
 
Ik zie slechts twee mogelijke antwoorden op deze vraag: ofwel wordt dit verboden, ofwel toegelaten maar enkel indien beide resultaten niet converteerbaar zijn (bv. er is geen norm voor het moleculair gewicht) of ze zijn via converteerbaar tot dezelfde waarde (rekening houden met het aantal beschikbare significante cijfers)
 
Daar er scenario’s zijn waarin het wenselijk is om op deze wijze te rapporteren, denk ik dat “verboden” niet de juiste keuze is.
 
Dit soort regel lijkt me een onderdeel te zijn van de standaard die we aan het opstellen zijn.
 
Tweede vraag: wat moet een ontvanger doen wanneer een verslag aangeleverd wordt met daarin meerdere resultaten voor één bepaling.
 
Kort antwoord: dat verslag moet zo getrouw mogelijk weergegeven worden, hetgeen betekent dat die herhaalde resultaten allen moeten voorgesteld worden met de eraan toegekende eenheid.
 
Dit lijkt me een normerend onderdeel te zijn van de homologatiecriteria van bv. de huisartspakketten en zou als advies kunnen opgenomen worden in onze standaard
 
Wanneer het ontvangend systeem meer doet met zo een verslag dan wel het eenvoudig weergeven op het scherm (bv. analyseren tot individuele resultaten om ze later op een tijdslijn te kunnen uitzetten) dan mag dit wel degelijk gebeuren mits er gebruik gemaakt wordt van de correcte conversie algoritmes en liefst genormeerde moleculaire gewichten.
 
Ook dit kan slechts als advies in onze standaard beschreven worden
 
Derde vraag: wanneer is het zinvol of aangeraden dat een labo-systeem een verslag aanmaakt met daarin twee resultaten voor één bepaling?
 
Wanneer het uitvoerend labo beslist (of verplicht wordt) om de eenheden waarin gerapporteerd wordt, te wijzigen, dan is het zeker zinvol om gedurende een zekere tijd resultaten in zowel de nieuwe als de oude eenheid te rapporteren.
 
Zijn er buiten dit scenario nog andere ?  Kunnen we in onze standaard adviseren dat dit het enige geldige scenario is?
 
Er is een gerelateerd scenario dat volgens mij duidelijk verschilt van dit en dat nog niet besproken werd: het uitvoerend labo neemt een nieuw toestel in gebruik, met een andere meetmethode, en het is onmogelijk om de kalibratie zodanig te doen dat over het gehele meetbereik de resultaten niet afwijken van de resultaten gemeten met het oude toestel.  Ook dan is het bijzonder zinvol om gedurende enige tijd de resultaten van beide toestellen naast mekaar in een verslag te zien.
 
Indien we dit zonder nadenken doen met de “gewone” mechanismen die voorzien zijn door onze standaard, gaan we één verslag krijgen met daarin twee resultaten met éénzelfde LOINC en UCUM maar met verschillende numerieke waarden.   Volgens de regel die hierboven voorgesteld werd, zou dit geen geldig verslag zijn.
 
Waarschijnlijk zal één van die twee resultaten geannoteerd zijn met een commentaar “opgelet, nieuwe meetmethode” en/of staat bij het andere resultaat misschien iets als “bekomen met de oude meetmethode”, maar het lijkt me moeilijk om dit soort commentaren in een standaard op te nemen.
 
Over dit laatste scenario zou best verder nagedacht worden.  Twee suggesties:
 
-        we houden ons aan de strikte regel, en stellen dat het resultaat dat ter vergelijking meegestuurd wordt in een commentaar beschreven wordt
-        we zoeken in de FHIR standaard naar een mechanisme waarmee we beide resultaten op gecodeerde manier van mekaar kunnen onderscheiden
 
Genoeg voor een maandag ochtend,
 
 
Joris Welkenhuysen
Team-lead labo development

UZ Leuven | campus Gasthuisberg | Herestraat 49 | 3000 Leuven - Belgium | btw BE 0419 052 173 | www.uzleuven.be |        
 
 
 
 
Onderwerp: RE: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Re-bonjour à tous 
 
Conversion d’unités – on la fait ou on ne la fait pas  – mais c’est pour le faire que l’on met les unités en UCUM !
Si le fournisseur de logiciel met un outil de conversion d’unité dans son logiciel, il ne peut pas en transférer la responsabilité au laboratoire émetteur (sauf convention dûment signée par les deux parties, ce qui me paraît peu réaliste)  (tous les juristes seront d’accord). 
Mais en effet il faut que l’émetteur collabore avec la validation du convertisseur , émetteur qui doit s’assurer que ses résultats sont correctement affichés – et là le récepteur doit avoir l’obligation de collaborer avec l’émetteur. Sauf erreur de ma part c’est une étape un peu oubliée de l’accréditation des logiciels de médecine ambulatoire et réellement à mettre à l’ordre du jour 
 
Le problème se limite un peu par l’usage des « unités préférentielles » que les laboratoires ont « l’obligation » d’utiliser , j’ai mis une liste en annexe (mais libre à eux d’en mettre une autre en plus) 
 
Bon dimanche, Philippe 
 
Dr Philippe CAUCHIE
CHU de Charleroi
 
Objet : Re: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Beste allemaal, 
 
Laat mij ook herhalen wat we in onze vorige technische meeting van woensdag hebben gezegd en het feit dat het niet de bedoeling kan (en mag) zijn om in een huisartsenpakket zelf herberekeningen te doen van de resultaten/eenheden die worden doorgegeven vanuit het labo. 
 
Zelfs indien de transformatie van de eenheden een vast algoritme is, dan nog zullen we aan de receiving kant (huisartsenpakketen etc) de letterlijke waarden moeten overnemen en tonen. 
Want de verantwoordelijkheid van wat er gedisplayed wordt, zal bij het labo/laborant moeten blijven (en niet worden overgedragen naar het GP pakket).  Ik denk dat zowel Stefan en Alin dit ook zo beschrijven in hun antwoorden. Correct?

Daarnaast, als het nodig is om resultaten van verschillende labo's voor patiënt X naast elkaar te kunnen vergelijken in een grafiek of tabel in het huisartsenpakket, dan zullen de gebruikte codes vanuit die verschillende labo's ook exact dezelfde analyse moeten representeren (dus zowel voor wat betreft de analyse code, maar ook de bijhorende eenheidscode). 
Dit was exact wat de up2date RETAM lijst beoogde in mijn opinie (ie. 1 lijst die op dezelfde manier door de labo's in België wordt gebruikt en die steeds uitbreidbaar is) en waar net ook de waarde van de hele huidige oefening en project ligt, lijkt me.

Stefan's voorstel om een aparte LOINC code te voorzien voor analyses met een andere eenheid, is het duidelijkste en veiligste voor receivers. Maar is het ook haalbaar voor de labo's om hun interne mappings naar de RETAM up2date te houden?
 
mvg
Filip
________________________________________
Onderwerp: RE: GITHUB - analyse in massa-eenheid en molaire eenheid 
 
Beste Tom,
Dan stuur je in de default eenheden op. Ik vermoed dat je dat op je papieren rapport ook doet.
 
Hoogachtend,
Dr. Alin Derom    Derval Services BV     

Onderwerp: Re: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Beste,
 
Wat betreft punt 3: de Hub kan ons een aanvraag sturen van Dr. Zusenzo, met wie wij nog nooit eerder samenwerkten, en waarvan wij dus niet weten welke eenheden hij mag verkiezen.  Dat blijft dus een probleem - tenzij we ofwel alles in 2 eenheden doorsturen, of ervan uitgaan dat de arts- en ziekenhuispaketten de omrekening doen.
 
Vriendelijke groeten,
 
Tom Tollenaere 
 
 
CIO MacSys
 
________________________________________
Subject: RE: GITHUB - analyse in massa-eenheid en molaire eenheid 
 
	OPGELET: Deze boodschap komt van een externe partij. Wees steeds voorzichtig bij het openen van bijlagen en links. 
Beste Stefan,
Voor punt 1 moet er dan beslist worden of de LOINC code van de alternatieve eenheid in de Retam tabel komt of niet. Wie beslist daarover?
Voor punt 2 : Vermits men ucum codes gebruikt kan (theoretisch) het HA-pakket de omrekening doen (zowel referentiewaarden als de resultaten) en dan alles naast elkaar zetten. Maar willen we dat? Wie moet dit valideren ? Soms zal er geen resultaat zijn doch een tekstuele opmerking zoals “Substantie is onmeetbaar laag (< 5 g/L)”. Dat staat in een tekstveld en zou dan wel onder elkaar moeten komen. Zien dat we het niet te moeilijk maken. 
Voor punt 3 : Indien de HUB u laat weten dat Dr Peeters een opvraging doet, dan deel je dit mee in de eenheden die je normaal gezien (op papier) aan dokter Peeters meedeelt. Ook dit punt moet bediscuteerd worden.
 
Hoogachtend,
Dr. Alin Derom    Derval Services BV     
 
Onderwerp: GITHUB - analyse in massa-eenheid en molaire eenheid
 
Tom, Philippe,
 
Even wat onduidelijkheid wegwerken rond het gebruik van massa-eenheden en molaire eenheden.
 
1)      Wensen we een resultaat in zowel mg/dL, als mmol/L in het FHIR-bericht te zetten, kunnen we dit doorgeven als 2 individuele resultaten. We dienen dan enkel in ons eigen systeem 2 loinc-codes te voorzien, dit om de conversie niet bij het artsenpakket te hoeven leggen. Ik vermoed dat dit vrij rechtlijnig is.
 
Vb.  Cholesterol in mg/dL:   2093-3 (retam/loinc)   of   Cholesterol in mmol/L:  14647-2 (loinc)
 
2)      Een moeilijker probleem, dat zich meer afspeelt aan de kant van de huisarts is het volgende: twee labo’s rapporteren analyse ‘retinol bindend proteïne’, beide gebruiken loinc 1836-6, maar gebruiken wel een andere ucum vb. mg/dL   en   g/L
 
Gaan we er dan van uit dat het huisartsenpakket analysen met een zelfde loinc, maar verschillende ucum, deze gaat behandelen als 2 verschillende analysen en deze niet samen zet in een historiek?
 
3)      Naar de toekomst toe dan i.k.v. HUB’s/metaHUB’s, neem ik dan ook aan dat het labo in zijn voorkeureenheden zal antwoorden op een pull request, en niet afhankelijk van de verschillende opvragers andere eenheden weergeeft (massa- of molaire eenheden)?
 
Mvg
 
Stefan
 
 
Dr. Stefan Waegemans 
Klinisch bioloog 
 
 
Centrum voor Medische Analyse bv

**Comment by alinderom** [comment]
Kennen jullie (eHealth) geen specialisten ter zake die kunnen uitleggen hoe bv thrombocyten op zowel EDTA als CITRAAT te rapporteren?

Of een Toxoplasmose IgM op 2 verschillende methodes?

Mobiel antwoord,  dus kort en ***@***.***

**Comment by bdc-ehealth** [comment]
Proposal visualisation workgroup:

Different LOINC code: no cumulative views
Same LOINC code, unit in UCUM and convertible: cumulative view allowed
Same LONC code, unit in UCUM and not convertible: no cumulative view allowed

Remark: when showing cumulative views, the reference values should be shown also

**Comment by alinderom** [comment]
Extra remark : the reference values AND THE UNIT must always (by default) be able to be shown, also in non cumulative views

**Comment by bdc-ehealth** [comment]
WG agrees: every lab will send the results in the units in which they have obtained the result.
