### ISSUE TITLE
Specimen test cases

### ISSUE THREAD

**Issue by ValerieNexuz** [hl7-be/lab#240]
There are some tetscases described for visualizing specimen. Is it necessary for GP softs to visualize these specimen? In de PDF version of de lab result these aren't shown. 

If GP softs need to show this information, is it needed to show this info per observation that's linked to the a specimen or in general show all specimen per labresult? Or do we need to show both as done in the visualization tool?

I can't find clear documentation on this topic. 

Linked testcases: 
- ID 35, 36, 37, 38 & 39

**Comment by bdc-ehealth** [comment]
@ValerieNexuz 
There are no explicit rules for visualizing specimens. The only criterion that will be handled during the minilab by the clinical biologists, is whether it is comprehensible for the GP/Patient . @tomfiers do you agree? So, if you at least display the information that is present on the PDF, you are safe.
