### ISSUE TITLE
Question regarding testcase ID 33 - label 4.4B

### ISSUE THREAD

**Issue by ValerieNexuz** [hl7-be/lab#241]
We try to process the labresult from testcase 33 but we get an error because the birthdate of the patiënt isn't matching the SSIN. Could the birthdate in this testcase be corrected or do we need to be able to process these kind of results?

**Comment by bdc-ehealth** [comment]
@ValerieNexuz ,

As the SSIN field can also contain a BIS-number, the birthdate of the patient will not always correspond with what is present in the SSIN-labeled identifier. Therefore we would suggest not to do this check on your side.
