### ISSUE TITLE
Test server failure scenario 4.2a

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#245]
Hi,

We get the following error when testing scenario 4.2a

"Bundle.entry.where(resource is Observation).resource.referenceRange.where(extension.where( url = 'https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition/be-ext-referencerange-comment' and (value as Annotation).text.exists() and (value as Annotation).extension.where(url = 'https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition/annotation-code' and (value as CodeableConcept).coding.where(code = 'lab-referencerange-comment').exists()).exists()).exists() ).exists()"

I assume this means that there needs to be a reference range comment in the JSON (which is not case). 
However, in GLIMS we do not have comments on the reference range. I thought this field was optional when we originally designed it? Currently, we fill referenceRange.text if there is a textual reference range. Is this test scenario too strict?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
@thibaultmh ,

you can selfdeclare this test as not applicable with the above justification.

**Comment by thibaultmh** [comment]
@bdc-ehealth thanks, I will close this
