### ISSUE TITLE
Category DiagnosticReport

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#25]
How should we categorise the protocol?  Standard (implementatiegids) indicates "possibly several categories" but those are not listed.  Proposal is to only use "Lab"

Addition question for phase 2: may we assume that anapath will be a separate category?

**Comment by bdc-ehealth** [comment]
@tomto66 Can you indicate where you found the reference to  "possibly several categories"

**Comment by thibaultmh** [comment]
We (MIPS) also use LAB for non-microbiology.

**Comment by bdc-ehealth** [comment]
WG agrees. No correction needed IG is already correct.
