### ISSUE TITLE
XML examples inconsistent  vs JSON

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#27]
We find different XML versions of FHIR Jason:  if we auto-translate JSON we get XML that is incompatible with the X:L examples in the implementation guide.  Differences are in terms of use of tags vs attributes.

Please clarify which XML approach is valid? Are both valid?

Link example in JSON: http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/Bundle-hematologyStudiesAsFHIRDocument.json.html
Example in XML: http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/Bundle-hematologyStudiesAsFHIRDocument.xml.html
Use this translator to get different X:L: https://www.freeformatter.com/json-to-xml-converter.html#ad-output

**Comment by bdc-ehealth** [comment]
FHIR has its own rules to create XML representations and JSON representations of its own resources. These are not the same as the rules that are used by https://www.freeformatter.com/json-to-xml-converter.html#ad-output . 

The rules of https://www.freeformatter.com/json-to-xml-converter.html#ad-output are not valid for FHIR.

HAPI FHIR is used to do this in Java: see this example: https://www.javahotchocolate.com/notes/fhir-converter.html
