### ISSUE TITLE
Validation of LOINC display names

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#278]
We have noticed today that the visualization tool is rejecting our messages when we send a LOINC code with a display name and the display name doesn't match one of the names expected by the server. If we leave the display name empty and send just the code, the message is successfully validated.

![error](https://github.com/hl7-be/lab/assets/97762183/bbd9cbfe-34a3-433d-bf9e-fdb9adef1c61)

I have following questions related to this:

- We believe that this kind of validation has been added very recently because we never noticed such kind of errors in the past. Can you confirm?
- Are the laboratories expected to send the LOINC display names as part of the FHIR bundle or is allowed or advised to leave it empty and include only the code?
- In case the display names are included in the messages, what is the reference database against which the tool is validating the names? The names published on loinc.org.
- It seems that the tool always expects the LOINC display names to be in English even if the main language of the report is indicated to be Dutch or French. Can you confirm?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

the conditions of the tests have not changed. At the moment we are facing a technical problem due to changes on the international terminology server.

The validation errors are invalid with respect to the agreements made in the HL7 Belgium Workgroup.

We are trying to find a solution.

**Comment by sebwautelet** [comment]
Hello @bdc-ehealth , do you have an update about this international terminology server issue? We cannot validate our remaining test cases because of this.

**Comment by bdc-ehealth** [comment]
@sebwautelet ,

On 11/11/2023, there was an upgrade on the international validator and in combination with an upgrade on the international terminology server on 16/02/2024, this causes the problems we are experiencing now. As there is no option to return to a stable situation (there are external components involved beyond our reach), we are working on a work-around. We hope to install it during next week, but as we are on unknown ground, we cannot guarantee a release moment.

**Comment by costateixeira** [comment]
For this issue please use the parameter display-warnings in the validator.

**Comment by bdc-ehealth** [comment]
@sebwautelet @frederic-istace 

There is a workaround for the "Wrong Display Name" problem. As you can see, the validation rules have become more strict since 11/11/2023. Due to a combination of factors, we could not stick to the older version of the validator, and we have had to upgrade. However, to keep the situation for this project stable, we will still accept files complying with the older rules, but we will display an additional warning sign. Further communication will indicate when the new international rules will be enforced for the lab project.

**Comment by frederic-istace** [comment]
@bdc-ehealth 
Do you know where we can find more information about these new international validation rules?

I just tried to upload an older test message to the visualizer and get a lot of error messages like this one that I never saw before:

Can't find 'Patient/1d23f18f-21d4-4615-b06c-fdad31767fd8' in the bundle (Composition.subject). Note that there are 1 resources in the bundle with the same type and id, but they do not match because of the fullUrl based rules around matching relative references (one of ``urn:uuid:1d23f18f-21d4-4615-b06c-fdad31767fd8``)

It's not very clear to me what they mean by "the fullUrl based rules around matching relative references". So, any help would be welcome.

**Comment by costateixeira** [comment]
To clarify, these are not new international rules, they were there from the
beginning, we just didn't follow them, and more recently this became
visible on the validator.
 There hasn't been any change to the rules.

**Comment by costateixeira** [comment]
thanks.
Please consult with Bart for the next actions;
I am just clarifying that the validator has been imposing stricter
terminology constraints for a while now, but it was never OK to use a
relative URL in the fullURL element.

**Comment by frederic-istace** [comment]
@bdc-ehealth 

I have been able to get rid of all the error messages containing the text "fullUrl based rules around matching relative references" by replacing all the references into our bundle as follow:
"reference": "Organization/64b9f4ab-8cef-44cf-acfb-10fa6075992c"
-->
"reference": "urn:uid:64b9f4ab-8cef-44cf-acfb-10fa6075992c"

However, I now get following error for every message I try to upload to the visualizer https://fhir-testserver.be/index.php/visualization_webapp:

![image](https://github.com/hl7-be/lab/assets/97762183/66138c4f-396b-46e6-9f3b-094f8a020453)

I don't really what's wrong with the patient identifier included in the bundle. So, I'm wondering if this is really a problem with my test message or a bug in the new version of the validator?

Example of a file related to test case 2F2 which is producing this error:

[82470091998_013G050038_l_2_MOLIS_4.json](https://github.com/hl7-be/lab/files/14164347/82470091998_013G050038_l_2_MOLIS_4.json)

This same file is still passing validation on the test server fhir-testserver.be

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

we will track this one here: https://github.com/ehealthplatformstandards/laboResultVisualization/issues/39
