### ISSUE TITLE
Can test case 8B be skipped if 8E is passed?

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#279]
Hi,

We do not have images on the report level in GLIMS. Instead we have images on the result level. For example an electrophorese graph would typically be an image result in our system. We can pass test case 8E but not 8B. Can we skip test case 8B?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
@thibaultmh , @kevinhacita

You can add N/A for this one... Please remember to refer to this issue if you are asked why you put N/A there.

**Comment by khackincita** [comment]
@bdc-ehealth : thank you :-)
