### ISSUE TITLE
Notion of "sequence number" on specimen

### ISSUE THREAD

**Issue by kjau** [hl7-be/lab#28]
It is required that our specimen can be identified by the sequence number of collection (specimen 1, 2, 3, ...). I notice the general FHIR profile has the extension "sequenceNumber" pre-defined, we will also need this in the BE Profile. 

ref:
https://www.hl7.org/fhir/extension-specimen-sequencenumber.html

**Comment by bdc-ehealth** [comment]
Add extension

**Comment by bdc-ehealth** [comment]
Do the MIPS people register this?
