### ISSUE TITLE
1D REF - `valueQuantity` should give a proper unit about the `value`

### ISSUE THREAD

**Issue by LotuxPunk** [hl7-be/lab#283]
In some cases of `valueQuantity` in this file, we can observe a lack of unit attached to the numerical value, whether it be in the `valueQuantity` or the `referenceRange`. It would be good to make the necessary modifications to encourage the presence of a unit for a measured value/reference value.

```json
"valueQuantity": {
  "value": 2.54
},
```

```json
"referenceRange": [
  {
    "low": {
      "value": 0.78
    },
    "high": {
      "value": 3.53
    },
    "text": "0,78 - 3,53"
  }
]
```

Also, some values have a unit, but do not have a Code pointing to UCUM even though it is a value present in UCUM.

```json
"valueQuantity": {
  "value": 0.03,
  "unit": "10³/µL"
},
```

**Comment by bdc-ehealth** [comment]
@LotuxPunk ,

can you give me the reference number of this file on the test server, I would like to take a look at it.

**Comment by LotuxPunk** [comment]
> @LotuxPunk ,
> 
> can you give me the reference number of this file on the test server, I would like to take a look at it.

It's the test case # 204, Patient with multiple surnames, label 1D

**Comment by LotuxPunk** [comment]
There's an improvement, but there's still not unit:
```
  "referenceRange": [
    {
      "low": {
        "value": 0.78,
        "system": "http://unitsofmeasure.org",
        "code": "{}"
      },
      "high": {
        "value": 3.53,
        "system": "http://unitsofmeasure.org",
        "code": "{}"
      },
      "text": "0,78 - 3,53"
    }
  ]
```

**Comment by bdc-ehealth** [comment]
@LotuxPunk 

the .unit field is not mandatory, but the code field is: https://www.ehealth.fgov.be/standards/fhir/lab/guidance.html#:~:text=If%20the%20FHIR%20datatype%20Quantity%20is%20used%2C%20the%20.code%20element%20SHALL%20be%20used.%20This%20element%20will%20also%20be%20shown%20by%20the%20visualizer%2C%20and%20not%20the%20.unit%20element.

The file is correct as it is now.

**Comment by LotuxPunk** [comment]
My bad, I misread the value of code. I thought it was an empty JSON object and not and "{}" string. Thank you very much !
