### ISSUE TITLE
Notion of "specimen was collected after 1 hour/120 minutes/1 week/..."

### ISSUE THREAD

**Issue by kjau** [hl7-be/lab#29]
There is a field "duration" in the Specimen resource that reprents "how long it took to collect the specimen". We will also need to code that "the specimen was collected after 1 hour/120 minutes/1 week/...". I do not find any reference to this kind of notation in the BE Profile or standard v4 FHIR specification.

**Comment by pcauchie** [comment]
this is typically a "dynamic test" for which there are special codes in LOINC

**Comment by bdc-ehealth** [comment]
If a LOINC code exists, we use it. Otherwise, we use the fallback-mechanism.

**Comment by bdc-ehealth** [comment]
WG the LOINC code must be used.
