### ISSUE TITLE
Consensus for microbiology reports?

### ISSUE THREAD

**Issue by SarahVandamme** [hl7-be/lab#299]
Dear colleagues,
 
We have some questions regarding the microbiology reports in FHIR. We have seen in the publicly shared testcases (thank you for this!) that every laboratory has developed its own way to code the testcases and visualize it through the tool as they see fit. Doing so, there is no consensus and it’s hard to know which one is the right way. Maybe there are several right ways? That’s why we have an example of a classic bacteriology report to open the discussion. You see our json file, and our pdf (how our clinicians view our reports).
[MI2311 0110.pdf](https://github.com/hl7-be/lab/files/14863185/MI2311.0110.pdf)
[81160393998_MI23110110_l_L_ITU_22.json](https://github.com/hl7-be/lab/files/14863192/81160393998_MI23110110_l_L_ITU_22.json)

Our questions are the following:
-	We tried to make our json file as technically correct as possible (still need to link the germ-ID’s). Is this **from a technical IT point of view** correct how we have coded this? 
-	**From a microbiological point of view** there are several things not optimal with the visualizer and this raises concerns how the software packages of the “receivers” will view our FHIR messages eventually:
o	How to deal with comments? As you can see in our pdf, we provide the clinician with comments regarding the germ, regarding the antibiogram and especially guide him/her in the right dosage when there’s an “I” result for an antibiotic. This is important information in the FHIR message, and is very clear in our pdf (one look for the clinician, one diagnosis). With the visualizer some clicks are needed to get to these comments. How are the software packages of the “receiver” going to deal with this?
o	There is no possibility to get multiple antibiograms in a consolidated (table) view. This means for a clinician a lot of scrolling up and down to pick the one antibiotic he/she would like to prescribe. To us this is a decline in quality. Would software packages of GP’s or other labs be able to reproduce a table or should we try to send it as figure?
o	The “I” is LOINC coded in our json, but this is translated as “intermediate resistant” which is an outdated and confusing term. We did not find a LOINC code which states the correct definition of “I”, namely “Susceptible, increased exposure”. Is anyone aware of a better LOINC code? We saw some examples by other labs, who simply report “I” and not the translation, yet this seems to be done textually? And we have no guarantee the receiving software will display it correctly when you correct it via text.
o	How to deal with MIC values? When we code it in our json file, we get two lines, one with the RSI, one with the MIC value. Can we be sure that the receiving software will pick up the MIC value? Is there a better way to transmit these kind of results?
 
To summarize: we can try to make it look nice in the visualizer provided right here, but how will the receiving software packages visualize it themselves? What is the correct way of writing your json file **so it gets interpreted correctly**?
Especially when we notice in published examples of testcases that labs map a LOINC for e.g. “bacterial culture from a wound specimen” but translate it to “aerobe kweek” (a more general term) via text field and display it as such in the visualizer. Is that risky or is that okay/allowed?
 
We have a lot of questions, but maybe we are not the only ones with these type of questions. Therefore we would like to suggest a separate microbiology FHIR meeting with all the key-players: eHealth, lab-IT/hospital IT, LIS providers, GP providers and microbiologists. Is this possible?

Kind regards,

Dr. Sarah Vandamme
Medical microbiologist
University Hospital Antwerp

**Comment by bdc-ehealth** [comment]
@SarahVandamme ,

It is important to clearly understand the scope of this project. This project is not aimed at defining a medical/clinical standard on how to harmonize and optimize lab results. That is a goal that can only be achieved by medical professionals like you, and not by computer scientists (which is what we are at eHealth).

All clinical and medical aspects of this project have been handled by clinical biologists and pathologists, such as @tomfiers (Tom Fiers UZGent), Philippe Cauchie CHC, Alin Derom/Veronique Stove from the professional organisation of clinical biologists, and some other volunteering biologists. If there are to be some further actions on harmonizing the clinical/medical aspects of the lab report, the initiative is on their (and your) side.

This project IS aimed at providing the technical means to enable both the sender and the receiver to use "structured" data, i.e. that is data that can be handled by a computer in a meaningful way without corrupting the contents and without the need of human interpretation for the most basic elements such as the identification of a test (by any code system, but preferably LOINC), the resulting value of the test (be it text or numeric), and the unit of the value (in the UCUM system of units, if applicable). Next to those elements there is ample opportunity to provide comments, reference ranges, etc... up to the inclusion  of a PDF report. This has been ascertained by the involved clinical biologists.

For this basic structuration we use the FHIR standard that we have adapted to the Belgian context during a number of open, publicly accessible sessions, of which also your hospital/lab was informed either directly, or indirectly by the professional organisation of clinical biologists.

The rendering of the information by the GP packages has been judged for their medical/clinical intelligibility by a clinical biologist during the so-called minilabs, or homologation for GP softwares. The aesthetic part of the rendering, however, is the responsibility of the GP softwares themselves, and it is the free choice of any GP to choose any software that was approved during the minilab (and was thus considered medically/clinically intelligible).

I hope that this explanation clarifies the (limited) scope of this project.

For your own files, if you have any questions or problems using the test tools, you can always push the "yellow" button to voice your concerns for a particular test, and together with the clinical biologists, I am convinced that we will find a solution.

**Comment by bdc-ehealth** [comment]
@SarahVandamme ,

for the detailed analysis of your file: 

I see that you propose following alternatives:

replace 17928-3 by 634-6 with explicit specimen
replace 17934-1 by 635-3 with explicit specimen

These replacements have been approved for other tests (with other types of specimen). Can we do this for this test as well @tomfiers?

**Comment by bdc-ehealth** [comment]
@SarahVandamme , if you resend this test, it should validate now.
