### ISSUE TITLE
Advice needed concerning the handling of the reference range in FHIR

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#300]
I'm unsure how we should fill the reference range in the FHIR observation resource from the data we have in our LIS in the context of the DIGIRELAB project in Belgium. 

Example of a paper report produced from our system

![PDF](https://github.com/hl7-be/lab/assets/97762183/95e85b79-45f8-4359-a333-bf7633e3584b)

If I fill the the result and the reference range of the observation like this in the FHIR

   {
      "fullUrl": "urn:uuid:e7b165b0-0209-4f23-b858-1b674ec6b034",
      "resource": {
        "resourceType": "Observation",
        "code": {
          "coding": [
            {
              "code": "GLU",
              "display": "Glucose",
              "system": "http://www.epicura.be/MOLIS/ANA"
            }
          ],
          "text": "Glucose"
        },
        "id": "e7b165b0-0209-4f23-b858-1b674ec6b034",
        "interpretation": [
          {
            "coding": [
              {
                "code": "H",
                "display": "High",
                "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              }
            ]
          }
        ],
        "issued": "2018-06-25T00:41:39+02:00",
        "meta": {
          "profile": [
            "https://www.ehealth.fgov.be/standards/fhir/lab/StructureDefinition/be-observation-laboratory"
          ]
        },
        "performer": [
          {
            "reference": "urn:uuid:d73917e5-f3c0-40fa-9fcb-000817e0facc"
          }
        ],
        "referenceRange": [
          {
            "high": {
              "unit": "mg/dL",
              "value": 100
            },
            "low": {
              "unit": "mg/dL",
              "value": 65
            }
          }
        ],
        "specimen": {
          "reference": "urn:uuid:fb53b6aa-0ac0-4ef8-b65f-966859cd60e1"
        },
        "status": "final",
        "subject": {
          "reference": "urn:uuid:e99f9697-e356-4e58-9566-5aeea7cdf50a"
        },
        "valueQuantity": {
          "unit": "mg/dL",
          "value": 103
        }
      }
    }

I get this output in the visualizer:

![high_low](https://github.com/hl7-be/lab/assets/97762183/06a366b4-9031-4565-8849-a52cabe2364e)

If I change the reference range in the FHIR like this:

        "referenceRange": [
          {
            "text": "65 - 100"
          }

I get following output in the visualizer which is much closer to our paper report:

![text](https://github.com/hl7-be/lab/assets/97762183/acbf75ea-cecf-4dd8-99b7-2d7b61f631ff)

So, which choice is the best?

As an IT guy, if I read the specification on https://build.fhir.org/observation-definitions.html#Observation.referenceRange ("Observation.referenceRange.text: Text based reference range in an observation which may be used when a quantitative range is not appropriate for an observation. An example would be a reference value of "Negative" or a list or table of "normals".), I would say the solution 1 is definitely the right to do it in FHIR.

However, if show the result we get in the visualizer to a biologist, most of them will probably prefer solution 2 for readability reasons. 

I don't know how the various GP systems will display the results received from us. During our initial tests as vendor, I was not very concerned by the output produced by the visualizer, but more by producing a FHIR message with structured data. However, in the meantime, I heard in a previous eHealth status meeting that at least one GP system was thinking about the possibility to use a local copy of the visualizer (available as open source software) to display the data instead of developing it themselves. 

So, should I more focus on being compatible with the international FHIR standard or getting an output in the visualizer which is as close as possible to the reports we produce on paper?

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

Your first solution is definitely the best. It is the responsibility of the (GP/Hospital) vendors to create a display that is readable for their users. In addition, the visualizer is only a development aid from the point of view of eHealth. It is open source and can be used by other parties, but only on their infrastructure and under their own responsability. So, don't be afraid to do better than the visualizer.

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Thank you. So, I keep solution 1.
