### ISSUE TITLE
Testcase 1A not loading patiënt

### ISSUE THREAD

**Issue by LievenVitaz** [hl7-be/lab#303]
Good afternoon, 

I've linked the JSON file I'm sending for test case 1A:

The test server doesn't want to evaluate the file and doesn't display the patiënt in the overview:
![image](https://github.com/hl7-be/lab/assets/167200207/e9a5d3fb-a405-430c-9453-896e1b5bcd97)
What is the issue ? 
[bundle_2405141523.json](https://github.com/hl7-be/lab/files/15309524/bundle_2405141523.json)

Kind regards, 

Lieven

**Comment by bdc-ehealth** [comment]
@LievenVitaz ,

Hello Lieven, we are aware of the problem, and we are looking in to it. We will come back to you as soon as possible.

**Comment by bdc-ehealth** [comment]
@LievenVitaz ,
Lieven, all your messages have been handled now! Thanks for the notification!
