### ISSUE TITLE
Create Logical Models for Message and Document

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/lab#39]
We have some example bundles and we even have Composition profile, but we don't have a MessageHeader profile for using in a Message architecture. 
**For both of these, we should add logical models - in this case, one LM for Document and another for Message.**

Later, such Logical Models may be taken up by HL7 Infrastructure - but for now we document them here, with very flexible constraints for the Labo reports.

**Comment by bdc-ehealth** [comment]
@costateixeira There was some unclarity in the group if it was really necessary to have a Message AND a Document version of the LabReport. The statement was that the information, both for the eHealthbox and the hubs/vaults was identical... (Even for information, such as people that received the original message - copy to physician ). How can we argue that we need both, apart from the needs described in https://docs.google.com/document/d/1uAmK0UROKemdkvkfRrFfnU30hWSeOn6q/edit#
