### ISSUE TITLE
Length of valueQuantity field (decimal)

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#42]
When the result is numerical, we are required to store it in a valueQuantity. The value-part of this item, is supposed to be a numerical field. Our results for different tests can be as long as up to 6 numbers after the decimal point. This is why we define this field as a decimal field with 6 places. However, for many tests, less decimals are required. Yet, as we use a decimal field, also for "shorter" required test results, the result will be shown with 6 decimals.
E.g.: result is 0.7 but will show as 0.700000

Is there a way this can be addressed? Using a valueString seems no option as a valueString doesn't work with unit fields.
The same question of course goes for the reference ranges for these results.

**Comment by bdc-ehealth** [comment]
FHIR expects this to be encoded in the right precision.

**Comment by aduchate** [comment]
The Visualization tool uses the precision provided in the actual observation. It does not make any assumption on the adequate precision.

**Comment by bdc-ehealth** [comment]
The precision transmitted in the FHIR message is the precision that is used by the lab during measurement. Neither visualisation or transmission can change the precision.
