### ISSUE TITLE
How to flag a receiver patient inversion events?

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#46]
This is loosely related to issue #18 (unique bundle identifiers): how shall a receiver deal with the following situation which happens frequently; here is the scenario:
* Lab sends results for order 123456, for patient Tom Tollenaere, 26/04/1966.
* Lab detects that a clerical error was made, and order 123456 is not for Tom Tollenaere, but for Stefan Waegemans, 24/03/1972.
* Lab sends a new bundle which gets integrated in physician software for Stefan Waegemans.
* BUT: how does physician know that previously sent results for Tom Tollenaere are invalid???

TODAY this is a problem for the whole industry.  Macsys/CMA/Medina flags this as a comment to the physician in the lab report, hinting that there is incorrect data for Tom Tollenaere.  But the lab does not control (cannot control) that the bad data for Tom Tollenaere gets deleted in the physician database!

We either leave this situation as is.  Or we try to find a way to automate removal of bad data.

This may be related to Issue #18: *if* the bundle Id for order 123456 is always the same (so if it does not change for different versions of the lab results) then the receiver can trace back, and remove any data previously sent for that bundle.   If every revision of a lab protocol results in a new bundle number then there is no way such corrections van be automated.

A solution may be to enforce that the Id of DiagnosticReport is unique per sender - and receiver may check (and undo) any previously sent values in previous bundles for same DiagnosticReport.

**Comment by bdc-ehealth** [comment]
As stated in #18 , it is indeed the identifier of the https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/StructureDefinition-be-laboratory-report.html that should be persistent. (If the identifier stays the same, it is a new version of the same report).

If a correction is sent (DiagnosticReport.status), then the receiving end can take action to correct/remove the previous data.

**Comment by tomto66** [comment]
The laboratory report is for us at both Composition level as well as DiagnosticReport and both use the same unique identifier.  Receiver may hence use Id of DiagnosticReport - example here: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/Macsys/20221119
