### ISSUE TITLE
LOINC code can appear twice in the same DiagnosticReport

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#51]
E.g. LOINC 94330-8 (Specimen Processing comment) can be used in multiple places in the report.

**Comment by bdc-ehealth** [comment]
@LotteAd Can you clarify this question a little? I am not sure what the problem is.

**Comment by LotteAd** [comment]
It's not really a question, rather a notification: some LOINC codes might appear more than once in the same report, mainly the LOINC codes we use for dummy analyses.

**Comment by LotteAd** [comment]
We found LOINC codes for most of our dummy analyses, you can see how we used these in our example 81365677998_815333046_5.json in the folder hl7-be-fhir-laboratory-report/testing/Macsys/20211124/

**Comment by bdc-ehealth** [comment]
WG checked that this approach is valid
