### ISSUE TITLE
Do we limit annexes to PDF? Do we allow multiple annexes?

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#60]
Do we make decisions about this, or do we leave this open.

FYI - Macsys ALWAYS embeds 1 pdf object in the FHIR, and that contains the protocol, including any annex pages to that protocol.  So annexes to the protocol are not separate embedded object in FHIR, they are part of the one pdf embedded in the FHIR.

Other senders may do this differently of course, and embed multiple annexes and/or embed document types other than PDF.

**Comment by bdc-ehealth** [comment]
Proposal JPG, PNG, PDF

Some people also use TIFF, BMP...

**Comment by bdc-ehealth** [comment]
1 PDF in presentedForm, andere PDFs of beelden in media...

**Comment by bdc-ehealth** [comment]
@ec-ehealth : when solving #136 check also this issue.
