### ISSUE TITLE
FHIR messages with large size

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#72]
An issue to discuss is that the size of FHIR messages increases rather fast, especially when adding annexes in their encoded form.
Bigger FHIR messages might cause delays and overhead when sending through eHealth boxes, which have a maximum capacity of 10MB, whereas we have already made FHIR messages of about 7 MB (with large annexes).

**Comment by costateixeira** [comment]
Perhaps it would be interestingh like to discuss the granularity of the lab report. In my view, we should be able to transmit the report, not necessarily the entire "letter" or set of documents that are needed. So if some images etc are acquired for the report, we can either 
a) always send them as attachment under the report, 
b) keep them as separate entities, and refer to them (or in some cases, bundle them together)
I would think b) is more appropriate - and this is why FHIR has not only the REST operations, but also Messaging and Documents. Both Messaging and Documents are Bundle-based and may present a good option to keep content separate when possible
An example of this is imaging - the imaging report for a CT cannot be a single resource with an attached file.

**Comment by bdc-ehealth** [comment]
issue was handled in https://be-ehealth-standards.atlassian.net/browse/ESI-55#icft=ESI-55
