### ISSUE TITLE
Visualizer excludes visualization of media

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#73]
According to the current scope the visualizer only manages the FHIR document, no other media. Is that what we want, do we need a scope extension.

Keep in mind that there an unlimited number of media types. We need to make the supported ones explicit... (also for the receiver type). Some media can be clinically relevant (Stefan Waegemans)...

**Comment by filipv-nh** [comment]
Suggestion to restrict the types of media that can be displayed to JPEG, PNG (and also perhaps PDF if requested by the labs).
This is for the field 'media' in DiagnosticReport.

**Comment by bdc-ehealth** [comment]
Proposal JPG, PNG, PDF

Some people also use TIFF, BMP, Word, PPT, MP4, XLS, CSV...

**Comment by thibaultmh** [comment]
For MIPS we would like to see:
BMP, JPG, TIF, GIF, PNG, TXT, HTM, XML, RTF, WAV, PDF, PS, DOC

**Comment by bdc-ehealth** [comment]
Proposal: only JPG, PNG, PDF, and no audio and video formats.
