### ISSUE TITLE
Concerning units: which is the "display" and which is the UCUM value?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#86]
![image](https://user-images.githubusercontent.com/93375157/151396976-4b42c175-0399-4be6-9e8a-30d67f46302f.png)

I believe "unit" would be the laboratory's own units and "code" the UCUM value?
Thank you for clarifying!

**Comment by bdc-ehealth** [comment]
Unit is the display value, code contains the UCUM unit.
