### ISSUE TITLE
Performer on Observation: why is cardinality 1..*

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#91]
In general the performer is the executing laboratory. This can also be added on report level. If the test is executed by a contractor, it is sometimes necessary to show the subcontractor. It would be overkill to always add the executing lab, if it is the own lab, because it is in the report. Therefore we would like to make the cardinality 0..*, so it is possible to only add the performer if it is a different subcontractor. Otherwise it is always the performer of the report.

**Comment by kjau** [comment]
Issue is missing on the Laboratory Project board Inbox?

**Comment by bdc-ehealth** [comment]
WG decides that the guidance must be modified:

diagnostic report: labo
interpreter: validator van het rapport
Composition.author: labo (niet verplicht)
Observation.performer: 0..* onderaannemer

**Comment by bdc-ehealth** [comment]
see: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/issues/100
