### ISSUE TITLE
Accreditation comment: what and how?

### ISSUE THREAD

**Issue by kjau** [hl7-be/lab#98]
**Problem**:
Currently, the profile for the [BeObservationLaboratory](https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/StructureDefinition-be-observation-laboratory.html) resource has a "[note](https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/StructureDefinition-be-observation-laboratory-definitions.html#Observation.note)" field of type [BeCodedAnnotation](https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/StructureDefinition-coded-annotation.html).

One of the annotation types is "[lab-test-accreditation](https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/CodeSystem-be-cs-coded-annotation-types.html#be-cs-coded-annotation-types-lab-test-accreditation)".

This gives us only the option to add an accredication comment on the result level.

**Questions**:
- What is required for accreditation from Belac? Do we need to **report** all the way down to the **result-level** inside the report?
- Do we need a **general** accreditation **comment for the entire report**? I was under the impression Belac requires us to set a general comment with a link/reference to a register with the detailed information on test-level of accreditation status.
- If we keep the accreditation comment on result level (so we do not restrict our options in case Belac does/also requires we send this information on the result-level), **what do we set as text for the comment on the test-level**? Woult it be too verbose to set the entire accreditation comment on each result? Is a general accreditation comment on DiagnosticReport level sufficient? The examples of Macsys put "yes/no" in this comment instead to reduce the verbosity.

**Comment by bdc-ehealth** [comment]
Do we agree with the method of Macsys, and add this to the guidance?

**Comment by thibaultmh** [comment]
Hi,

About point 3, we at MIPS use free text. We do not agree that it is too verbose. Why not put the field under the observation details in the vizualizer?

**Comment by kjau** [comment]
Oh I was not making the comment because of the Visualizer. May I ask what text you will put in the comment? So we have an example from Macsys and from MIPS.

It is totally OK for me to put the full comment in each note, we just have to make things clear in the guidance as Macsys will not put a full comment in the note.

**Comment by thibaultmh** [comment]
For example, instead of 'yes' you might see 'Geaccrediteerd door Belac', 'BELAC' or something. Each lab has his own way of doing things.

**Comment by kjau** [comment]
At UZLeuven we also use a full text, refering to the public "labogids" for detailed information on accreditation. This comment is at the general level of the DiagnosticReport, not at the detailed level of Observation. The text can be configured and customized by the lab responsibles themselves.
